if VehicleZoneDistribution then

    VehicleZoneDistribution.parkingstall.vehicles["Base.SC_FordExplorer"] = {index = -1, spawnChance = 5};
    VehicleZoneDistribution.parkingstall.vehicles["Base.SC_FordTaurus"] = {index = -1, spawnChance = 15};
    VehicleZoneDistribution.parkingstall.vehicles["Base.SC_HondaAccord"] = {index = -1, spawnChance = 15};
    VehicleZoneDistribution.parkingstall.vehicles["Base.SC_VWRabbit"] = {index = -1, spawnChance = 15};
    VehicleZoneDistribution.parkingstall.vehicles["Base.SC_MazdaB2000"] = {index = -1, spawnChance = 15};
    VehicleZoneDistribution.parkingstall.vehicles["Base.SC_FordCrownVictoria85"] = {index = -1, spawnChance = 10};
    VehicleZoneDistribution.parkingstall.vehicles["Base.SC_FordCrownVictoria85_Taxi"] = {index = -1, spawnChance = 1};
    VehicleZoneDistribution.parkingstall.vehicles["Base.SC_FordCrownVictoria85_StatePolice"] = {index = -1, spawnChance = 1};
    VehicleZoneDistribution.parkingstall.vehicles["Base.SC_FordCrownVictoria85_ParkRanger"] = {index = -1, spawnChance = 0.2};
    VehicleZoneDistribution.parkingstall.vehicles["Base.SC_FordCrownVictoria92_"] = {index = -1, spawnChance = 1};
    VehicleZoneDistribution.parkingstall.vehicles["Base.SC_FordF350Ambulance"] = {index = -1, spawnChance = 0.001};
    VehicleZoneDistribution.parkingstall.vehicles["Base.SC_GrummanLLV"] = {index = -1, spawnChance = 0.2};
    VehicleZoneDistribution.parkingstall.vehicles["Base.SC_CadillacFleetwoodBrougham"] = {index = -1, spawnChance = 1};
    VehicleZoneDistribution.parkingstall.vehicles["Base.SC_BMW520i"] = {index = -1, spawnChance = 0.5};
    VehicleZoneDistribution.parkingstall.vehicles["Base.SC_Porsche911"] = {index = -1, spawnChance = 0.5};
    VehicleZoneDistribution.parkingstall.vehicles["Base.SC_JeepCJ7"] = {index = -1, spawnChance = 1};
    VehicleZoneDistribution.parkingstall.vehicles["Base.SC_JeepCherokee"] = {index = -1, spawnChance = 5};
    VehicleZoneDistribution.parkingstall.vehicles["Base.SC_JeepGrandWagoneer"] = {index = -1, spawnChance = 5};
    VehicleZoneDistribution.parkingstall.vehicles["Base.SC_GMCJimmyS15"] = {index = -1, spawnChance = 5};
    VehicleZoneDistribution.parkingstall.vehicles["Base.SC_NissanPathfinder"] = {index = -1, spawnChance = 5};
    VehicleZoneDistribution.parkingstall.vehicles["Base.SC_PlymouthVoyager"] = {index = -1, spawnChance = 0.5};
    VehicleZoneDistribution.parkingstall.vehicles["Base.SC_VWRabbit_Pizza"] = {index = -1, spawnChance = 1};
    VehicleZoneDistribution.parkingstall.vehicles["Base.SC_GeoTracker"] = {index = -1, spawnChance = 5};
    VehicleZoneDistribution.parkingstall.vehicles["Base.SC_Mercedes280"] = {index = -1, spawnChance = 0.5};
    VehicleZoneDistribution.parkingstall.vehicles["Base.SC_FordBronco"] = {index = -1, spawnChance = 5};
    VehicleZoneDistribution.parkingstall.vehicles["Base.SC_FordF15092"] = {index = -1, spawnChance = 5};
    VehicleZoneDistribution.parkingstall.vehicles["Base.SC_FordMustang90"] = {index = -1, spawnChance = 5};
    VehicleZoneDistribution.parkingstall.vehicles["Base.SC_FordMustang90_StatePolice"] = {index = -1, spawnChance = 0.5};
    VehicleZoneDistribution.parkingstall.vehicles["Base.SC_FordMustang90_Undercover"] = {index = -1, spawnChance = 0.2};
    VehicleZoneDistribution.parkingstall.vehicles["Base.SC_ChevroletK5Blazer"] = {index = -1, spawnChance = 5};
    VehicleZoneDistribution.parkingstall.vehicles["Base.SC_ChevroletK5Blazer_Fossoil"] = {index = -1, spawnChance = 1};
    VehicleZoneDistribution.parkingstall.vehicles["Base.SC_ChevroletK5Blazer_McCoys"] = {index = -1, spawnChance = 1};
    VehicleZoneDistribution.parkingstall.vehicles["Base.SC_ChevroletK5Blazer_ParkRanger"] = {index = -1, spawnChance = 0.5};
    VehicleZoneDistribution.parkingstall.vehicles["Base.SC_ChevroletCaprice85"] = {index = -1, spawnChance = 15};
    VehicleZoneDistribution.parkingstall.vehicles["Base.SC_ChevroletSuburban"] = {index = -1, spawnChance = 0.5};
    VehicleZoneDistribution.parkingstall.vehicles["Base.SC_ChevroletCavalier"] = {index = -1, spawnChance = 15};
    VehicleZoneDistribution.parkingstall.vehicles["Base.SC_ChevroletCamaro87"] = {index = -1, spawnChance = 1};
    VehicleZoneDistribution.parkingstall.vehicles["Base.SC_ChevroletP30"] = {index = -1, spawnChance = 1};
    VehicleZoneDistribution.parkingstall.vehicles["Base.SC_ChevroletP30_Mail"] = {index = -1, spawnChance = 0.1};
    VehicleZoneDistribution.parkingstall.vehicles["Base.SC_ChevroletP30_Heralds"] = {index = -1, spawnChance = 0.1};
    VehicleZoneDistribution.parkingstall.vehicles["Base.SC_ChevroletP30_Scarlet"] = {index = -1, spawnChance = 0.1};
    VehicleZoneDistribution.parkingstall.vehicles["Base.SC_ChevroletP30_BunnyBread"] = {index = -1, spawnChance = 0.3};
    VehicleZoneDistribution.parkingstall.vehicles["Base.SC_ChevroletP30_Greenes"] = {index = -1, spawnChance = 0.3};
    VehicleZoneDistribution.parkingstall.vehicles["Base.SC_ChevroletG30_"] = {index = -1, spawnChance = 1};
    VehicleZoneDistribution.parkingstall.vehicles["Base.SC_ChevroletG30_Seats"] = {index = -1, spawnChance = 1};
    VehicleZoneDistribution.parkingstall.vehicles["Base.SC_ChevroletG30_Mail"] = {index = -1, spawnChance = 1};
    VehicleZoneDistribution.parkingstall.vehicles["Base.SC_ChevroletG30_McCoy"] = {index = -1, spawnChance = 1};
    VehicleZoneDistribution.parkingstall.vehicles["Base.SC_ChevroletG30_Spiffo"] = {index = -1, spawnChance = 1};
    VehicleZoneDistribution.parkingstall.vehicles["Base.SC_ChevroletG30_Fossoil"] = {index = -1, spawnChance = 1};
    VehicleZoneDistribution.parkingstall.vehicles["Base.SC_ChevroletG30_LectroMax"] = {index = -1, spawnChance = 1};
    VehicleZoneDistribution.parkingstall.vehicles["Base.SC_ChevroletG30_MassGenFac"] = {index = -1, spawnChance = 1};
    VehicleZoneDistribution.parkingstall.vehicles["Base.SC_ChevroletG30_Ambulance"] = {index = -1, spawnChance = 0.001};
    VehicleZoneDistribution.parkingstall.vehicles["Base.SC_ChevroletG30_SpecialForces"] = {index = -1, spawnChance = 0.1};
    VehicleZoneDistribution.parkingstall.vehicles["Base.SC_ChevroletG30_BoxVan"] = {index = -1, spawnChance = 0.5};
    VehicleZoneDistribution.parkingstall.vehicles["Base.SC_FordF700BoxTruck"] = {index = -1, spawnChance = 0.5};
    VehicleZoneDistribution.parkingstall.vehicles["Base.SC_FordF700BoxTruck_MacTools"] = {index = -1, spawnChance = 0.5};       
    VehicleZoneDistribution.parkingstall.vehicles["Base.SC_FordF700BoxTruck_GigaMart"] = {index = -1, spawnChance = 0.5};     
    VehicleZoneDistribution.parkingstall.vehicles["Base.SC_FordF700BoxTruck_Greenes"] = {index = -1, spawnChance = 0.5};
    VehicleZoneDistribution.parkingstall.vehicles["Base.SC_FordF700BoxTruck_BunnyBread"] = {index = -1, spawnChance = 0.5};
    VehicleZoneDistribution.parkingstall.vehicles["Base.SC_FordF700BoxTruck_Ryder"] = {index = -1, spawnChance = 0.5};     
    VehicleZoneDistribution.parkingstall.vehicles["Base.SC_FordF700BoxTruck_Mayflower"] = {index = -1, spawnChance = 0.5};
    VehicleZoneDistribution.parkingstall.vehicles["Base.SC_FordF700BoxTruck_Budget"] = {index = -1, spawnChance = 0.5}
    VehicleZoneDistribution.parkingstall.vehicles["Base.SC_FordF700Armored_Dunbar"] = {index = -1, spawnChance = 0.1}
    VehicleZoneDistribution.parkingstall.vehicles["Base.SC_FordF700Armored_Brinks"] = {index = -1, spawnChance = 0.1}
    VehicleZoneDistribution.parkingstall.vehicles["Base.SC_FordF700Armored_Transport"] = {index = -1, spawnChance = 0.1}
    VehicleZoneDistribution.parkingstall.vehicles["Base.SC_FordF700DumpTruck"] = {index = -1, spawnChance = 0.5};    
    VehicleZoneDistribution.parkingstall.vehicles["Base.SC_MackDM800Garbage"] = {index = -1, spawnChance = 0.2};       
    VehicleZoneDistribution.parkingstall.vehicles["Base.SC_SmallUtilityTrailer"] = {index = -1, spawnChance = 1};   
    VehicleZoneDistribution.parkingstall.vehicles["Base.SC_MediumEnclosedTrailer"] = {index = -1, spawnChance = 1};  
    VehicleZoneDistribution.parkingstall.chanceToPartDamage = 10;
    
    VehicleZoneDistribution.spiffo.vehicles["Base.SC_ChevroletG30_Spiffo"] = {index = -1, spawnChance = 1};  
    VehicleZoneDistribution.spiffo.chanceToPartDamage = 5;

    VehicleZoneDistribution.medium.vehicles["Base.SC_ChevroletP30_Greenes"] = {index = -1, spawnChance = 1};
    VehicleZoneDistribution.medium.vehicles["Base.SC_ChevroletP30_BunnyBread"] = {index = -1, spawnChance = 1};
    VehicleZoneDistribution.medium.vehicles["Base.SC_FordF700BoxTruck_MacTools"] = {index = -1, spawnChance = 1};
    VehicleZoneDistribution.medium.vehicles["Base.SC_FordF700BoxTruck_GigaMart"] = {index = -1, spawnChance = 1};
    VehicleZoneDistribution.medium.vehicles["Base.SC_FordF700BoxTruck_Greenes"] = {index = -1, spawnChance = 1};
    VehicleZoneDistribution.medium.vehicles["Base.SC_FordF700BoxTruck_BunnyBread"] = {index = -1, spawnChance = 1};
    VehicleZoneDistribution.medium.vehicles["Base.SC_FordF700PanelTruck"] = {index = -1, spawnChance = 1};
    VehicleZoneDistribution.medium.vehicles["Base.SC_FordF700DumpTruck"] = {index = -1, spawnChance = 1};
    VehicleZoneDistribution.medium.vehicles["Base.SC_ChevroletCaprice85"] = {index = -1, spawnChance = 15};
    VehicleZoneDistribution.medium.vehicles["Base.SC_SmallUtilityTrailer"] = {index = -1, spawnChance = 1};
    VehicleZoneDistribution.medium.vehicles["Base.SC_MediumEnclosedTrailer"] = {index = -1, spawnChance = 1};
    VehicleZoneDistribution.medium.chanceToPartDamage = 10;
    
    VehicleZoneDistribution.good.vehicles["Base.SC_ChevroletP30_Greenes"] = {index = -1, spawnChance = 0.5};
    VehicleZoneDistribution.good.vehicles["Base.SC_ChevroletP30_BunnyBread"] = {index = -1, spawnChance = 0.5};
    VehicleZoneDistribution.good.vehicles["Base.SC_ChevroletCaprice85"] = {index = -1, spawnChance = 35};
    VehicleZoneDistribution.good.vehicles["Base.SC_JeepCherokee"] = {index = -1, spawnChance = 35};
    VehicleZoneDistribution.good.vehicles["Base.SC_JeepGrandWagoneer"] = {index = -1, spawnChance = 35};
    VehicleZoneDistribution.good.vehicles["Base.SC_GMCJimmyS15"] = {index = -1, spawnChance = 35};
    VehicleZoneDistribution.good.vehicles["Base.SC_NissanPathfinder"] = {index = -1, spawnChance = 35};
    VehicleZoneDistribution.good.vehicles["Base.SC_MazdaB2000"] = {index = -1, spawnChance = 35};
    VehicleZoneDistribution.good.vehicles["Base.SC_GeoTracker"] = {index = -1, spawnChance = 35};
    VehicleZoneDistribution.good.vehicles["Base.SC_FordF15092"] = {index = -1, spawnChance = 35};
    VehicleZoneDistribution.good.vehicles["Base.SC_FordBronco"] = {index = -1, spawnChance = 35};
    VehicleZoneDistribution.good.vehicles["Base.SC_PlymouthVoyager"] = {index = -1, spawnChance = 30};
    VehicleZoneDistribution.good.vehicles["Base.SC_Porsche911"] = {index = -1, spawnChance = 5};
    VehicleZoneDistribution.good.vehicles["Base.SC_FordMustang90"] = {index = -1, spawnChance = 25};
    VehicleZoneDistribution.good.vehicles["Base.SC_Mercedes280"] = {index = -1, spawnChance = 10};
    VehicleZoneDistribution.good.vehicles["Base.SC_BMW520i"] = {index = -1, spawnChance = 5};
    VehicleZoneDistribution.good.vehicles["Base.SC_FordTaurus"] = {index = -1, spawnChance = 25};
    VehicleZoneDistribution.good.vehicles["Base.SC_ChevroletCavalier"] = {index = -1, spawnChance = 25};
    VehicleZoneDistribution.good.baseVehicleQuality = 1.1;
    VehicleZoneDistribution.good.chanceToPartDamage = 5;

    VehicleZoneDistribution.sport.vehicles["Base.SC_FordMustang90"] = {index = -1, spawnChance = 70};
    VehicleZoneDistribution.sport.vehicles["Base.SC_FordBronco"] = {index = -1, spawnChance = 70};
    VehicleZoneDistribution.sport.vehicles["Base.SC_Porsche911"] = {index = -1, spawnChance = 10};
    VehicleZoneDistribution.sport.vehicles["Base.SC_JeepCherokee"] = {index = -1, spawnChance = 70};
    VehicleZoneDistribution.sport.vehicles["Base.SC_BMW520i"] = {index = -1, spawnChance = 50};
    VehicleZoneDistribution.sport.vehicles["Base.SC_CadillacFleetwoodBrougham"] = {index = -1, spawnChance = 80};
    VehicleZoneDistribution.sport.vehicles["Base.SC_ChevroletSuburban"] = {index = -1, spawnChance = 50};
    VehicleZoneDistribution.sport.vehicles["Base.SC_ChevroletCamaro87"] = {index = -1, spawnChance = 50};
    VehicleZoneDistribution.sport.baseVehicleQuality = 1.1;
    VehicleZoneDistribution.sport.chanceToPartDamage = 5;

    VehicleZoneDistribution.police.vehicles["Base.SC_ChevroletP30_SWAT"] = {index = -1, spawnChance = 1};
    VehicleZoneDistribution.police.vehicles["Base.SC_ChevroletSuburbanStatePolice"] = {index = -1, spawnChance = 15};
    VehicleZoneDistribution.police.vehicles["Base.SC_FordMustang90_JeffersonPolice"] = {index = -1, spawnChance = 30};
    VehicleZoneDistribution.police.vehicles["Base.SC_FordMustang90_StatePolice"] = {index = -1, spawnChance = 30};
    VehicleZoneDistribution.police.vehicles["Base.SC_FordMustang90_Undercover"] = {index = -1, spawnChance = 30};
    VehicleZoneDistribution.police.vehicles["Base.SC_FordCrownVictoria85_StatePolice"] = {index = -1, spawnChance = 50};
    VehicleZoneDistribution.police.vehicles["Base.SC_FordCrownVictoria92_Jefferson"] = {index = -1, spawnChance = 30};
    VehicleZoneDistribution.police.vehicles["Base.SC_FordCrownVictoria92_Muhlen"] = {index = -1, spawnChance = 30};
    VehicleZoneDistribution.police.vehicles["Base.SC_FordCrownVictoria92_Warren"] = {index = -1, spawnChance = 30};
    VehicleZoneDistribution.police.vehicles["Base.SC_FordCrownVictoria92_Meade"] = {index = -1, spawnChance = 30};
    VehicleZoneDistribution.police.baseVehicleQuality = 1.1;
    VehicleZoneDistribution.police.chanceToPartDamage = 5;

    VehicleZoneDistribution.postal.vehicles["Base.SC_GrummanLLV"] = {index = -1, spawnChance = 100};
    VehicleZoneDistribution.postal.vehicles["Base.SC_ChevroletP30_Mail"] = {index = -1, spawnChance = 25};
    VehicleZoneDistribution.postal.vehicles["Base.SC_ChevroletG30_Mail"] = {index = -1, spawnChance = 25};
    VehicleZoneDistribution.postal.chanceToPartDamage = 5;

    VehicleZoneDistribution.mccoy.vehicles["Base.SC_FordF700BoxTruck"] = {index = -1, spawnChance = 5};
    VehicleZoneDistribution.mccoy.vehicles["Base.SC_FordF700PanelTruck"] = {index = -1, spawnChance = 25};
    VehicleZoneDistribution.mccoy.vehicles["Base.SC_FordF700DumpTruck"] = {index = -1, spawnChance = 25};
    VehicleZoneDistribution.mccoy.vehicles["Base.SC_ChevroletG30_McCoy"] = {index = -1, spawnChance = 25};
    VehicleZoneDistribution.mccoy.vehicles["Base.SC_ChevroletG30_BoxVan"] = {index = -1, spawnChance = 25};
    VehicleZoneDistribution.mccoy.vehicles["Base.SC_ChevroletK5BlazerMcCoys"] = {index = -1, spawnChance = 50};
    VehicleZoneDistribution.mccoy.vehicles["Base.SC_SmallUtilityTrailer"] = {index = -1, spawnChance = 25};
    VehicleZoneDistribution.mccoy.chanceToPartDamage = 25;
    
    VehicleZoneDistribution.trailerpark.vehicles["Base.SC_SmallUtilityTrailer"] = {index = -1, spawnChance = 10};
    VehicleZoneDistribution.trailerpark.vehicles["Base.SC_MediumEnclosedTrailer"] = {index = -1, spawnChance = 10};  
    VehicleZoneDistribution.trailerpark.chanceToPartDamage = 25;

    VehicleZoneDistribution.knoxdisti.vehicles["Base.SC_ChevroletP30_Disti"] = {index = -1, spawnChance = 30};
    VehicleZoneDistribution.knoxdisti.vehicles["Base.SC_FordCrownVictoria85_LouisvillePolice"] = {index = -1, spawnChance = 5};
    VehicleZoneDistribution.knoxdisti.vehicles["Base.SC_FordCrownVictoria92_LouisvillePolice"] = {index = -1, spawnChance = 5};
    VehicleZoneDistribution.knoxdisti.vehicles["Base.SC_FordCrownVictoria92_JeffersonPolice"] = {index = -1, spawnChance = 5};
    VehicleZoneDistribution.knoxdisti.vehicles["Base.SC_JeepCherokee_Audubon"] = {index = -1, spawnChance = 10};
    VehicleZoneDistribution.knoxdisti.chanceToPartDamage = 5;

    VehicleZoneDistribution.massgenfac.vehicles["Base.SC_ChevroletG30_MassGenFac"] = {index = -1, spawnChance = 30};
    VehicleZoneDistribution.massgenfac.vehicles["Base.SC_FordMustang90_JeffersonPolice"] = {index = -1, spawnChance = 5};
    VehicleZoneDistribution.massgenfac.vehicles["Base.SC_FordCrownVictoria85_LouisvillePolice"] = {index = -1, spawnChance = 5};
    VehicleZoneDistribution.massgenfac.vehicles["Base.SC_FordCrownVictoria92_LouisvillePolice"] = {index = -1, spawnChance = 5};
    VehicleZoneDistribution.massgenfac.vehicles["Base.SC_JeepCherokee_Audubon"] = {index = -1, spawnChance = 5};
    VehicleZoneDistribution.massgenfac.vehicles["Base.SC_ChevroletG30_BoxVan"] = {index = -1, spawnChance = 25};
    VehicleZoneDistribution.massgenfac.chanceToPartDamage = 10;

    VehicleZoneDistribution.network3.vehicles["Base.SC_FordMustang90_JeffersonPolice"] = {index = -1, spawnChance = 5};
    VehicleZoneDistribution.network3.vehicles["Base.SC_FordCrownVictoria85_LouisvillePolice"] = {index = -1, spawnChance = 5};
    VehicleZoneDistribution.network3.vehicles["Base.SC_FordCrownVictoria92_LouisvillePolice"] = {index = -1, spawnChance = 5};
    VehicleZoneDistribution.network3.vehicles["Base.SC_JeepCherokee_Audubon"] = {index = -1, spawnChance = 10};
    VehicleZoneDistribution.network3.chanceToPartDamage = 5;

    VehicleZoneDistribution.kyheralds.vehicles["Base.SC_ChevroletP30_Heralds"] = {index = -1, spawnChance = 30};
    VehicleZoneDistribution.kyheralds.vehicles["Base.SC_FordMustang90_JeffersonPolice"] = {index = -1, spawnChance = 5};
    VehicleZoneDistribution.kyheralds.vehicles["Base.SC_FordCrownVictoria85_LouisvillePolice"] = {index = -1, spawnChance = 5};
    VehicleZoneDistribution.kyheralds.vehicles["Base.SC_FordCrownVictoria92_LouisvillePolice"] = {index = -1, spawnChance = 5};
    VehicleZoneDistribution.kyheralds.vehicles["Base.SC_JeepCherokee_Audubon"] = {index = -1, spawnChance = 10};
    VehicleZoneDistribution.kyheralds.chanceToPartDamage = 5;

    VehicleZoneDistribution.junkyard.vehicles["Base.SC_FordF700PanelTruck"] = {index = -1, spawnChance = 5};  
    VehicleZoneDistribution.junkyard.vehicles["Base.SC_FordF700BoxTruck"] = {index = -1, spawnChance = 5};  
    VehicleZoneDistribution.junkyard.vehicles["Base.SC_FordF700DumpTruck"] = {index = -1, spawnChance = 5};  
    VehicleZoneDistribution.junkyard.vehicles["Base.SC_ChevroletG30_SpecialForces"] = {index = -1, spawnChance = 5};  
    VehicleZoneDistribution.junkyard.chanceToPartDamage = 60;
    
    VehicleZoneDistribution.trafficjams.vehicles["Base.SC_ChevroletM1008"] = {index = -1, spawnChance = 5};
    VehicleZoneDistribution.trafficjams.vehicles["Base.SC_ChevroletM1008TroopCarrier"] = {index = -1, spawnChance = 5};
    VehicleZoneDistribution.trafficjams.vehicles["Base.SC_ChevroletM1009"] = {index = -1, spawnChance = 5};
    VehicleZoneDistribution.trafficjams.vehicles["Base.SC_ChevroletM1009MP"] = {index = -1, spawnChance = 5};
    VehicleZoneDistribution.trafficjams.vehicles["Base.SC_ChevroletM1010Ambulance"] = {index = -1, spawnChance = 5};
    
    VehicleZoneDistribution.trafficjamn.vehicles["Base.SC_AMGeneralM998"] = {index = -1, spawnChance = 5};
    VehicleZoneDistribution.trafficjamn.vehicles["Base.SC_AMGeneralM1025"] = {index = -1, spawnChance = 5};
    VehicleZoneDistribution.trafficjamn.vehicles["Base.SC_AMGeneralM1025MP"] = {index = -1, spawnChance = 5};

    VehicleZoneDistribution.trafficjamn.vehicles["Base.SC_AMGeneralM1097TroopCarrier"] = {index = -1, spawnChance = 5};
    VehicleZoneDistribution.trafficjamn.vehicles["Base.SC_AMGeneralM997Ambulance"] = {index = -1, spawnChance = 5};
    VehicleZoneDistribution.trafficjamn.vehicles["Base.SC_AMGeneralM997"] = {index = -1, spawnChance = 5};
    VehicleZoneDistribution.trafficjamn.vehicles["Base.SC_AMGeneralM997Tan"] = {index = -1, spawnChance = 1};
    VehicleZoneDistribution.trafficjamn.vehicles["Base.SC_AMGeneralM997Green"] = {index = -1, spawnChance = 5};

    VehicleZoneDistribution.trafficjamn.vehicles["Base.SC_FordExplorer"] = {index = -1, spawnChance = 5};
    VehicleZoneDistribution.trafficjamn.vehicles["Base.SC_FordTaurus"] = {index = -1, spawnChance = 15};
    VehicleZoneDistribution.trafficjamn.vehicles["Base.SC_HondaAccord"] = {index = -1, spawnChance = 15};
    VehicleZoneDistribution.trafficjamn.vehicles["Base.SC_VWRabbit"] = {index = -1, spawnChance = 15};
    VehicleZoneDistribution.trafficjamn.vehicles["Base.SC_MazdaB2000"] = {index = -1, spawnChance = 10};
    VehicleZoneDistribution.trafficjamn.vehicles["Base.SC_FordCrownVictoria85"] = {index = -1, spawnChance = 10};
    VehicleZoneDistribution.trafficjamn.vehicles["Base.SC_FordCrownVictoria85_Taxi"] = {index = -1, spawnChance = 1};
    VehicleZoneDistribution.trafficjamn.vehicles["Base.SC_FordCrownVictoria85_StatePolice"] = {index = -1, spawnChance = 1};
    VehicleZoneDistribution.trafficjamn.vehicles["Base.SC_FordCrownVictoria85_ParkRanger"] = {index = -1, spawnChance = 1};
    VehicleZoneDistribution.trafficjamn.vehicles["Base.SC_FordF350Ambulance"] = {index = -1, spawnChance = 10};
    VehicleZoneDistribution.trafficjamn.vehicles["Base.SC_GrummanLLV"] = {index = -1, spawnChance = 5};
    VehicleZoneDistribution.trafficjamn.vehicles["Base.SC_JeepCJ7"] = {index = -1, spawnChance = 5};
    VehicleZoneDistribution.trafficjamn.vehicles["Base.SC_JeepCherokee"] = {index = -1, spawnChance = 5};
    VehicleZoneDistribution.trafficjamn.vehicles["Base.SC_PlymouthVoyager"] = {index = -1, spawnChance = 10};
    VehicleZoneDistribution.trafficjamn.vehicles["Base.SC_VWRabbit_Pizza"] = {index = -1, spawnChance = 5};
    VehicleZoneDistribution.trafficjamn.vehicles["Base.SC_GeoTracker"] = {index = -1, spawnChance = 10};
    VehicleZoneDistribution.trafficjamn.vehicles["Base.SC_FordBronco"] = {index = -1, spawnChance = 6};
    VehicleZoneDistribution.trafficjamn.vehicles["Base.SC_FordF15092"] = {index = -1, spawnChance = 5};
    VehicleZoneDistribution.trafficjamn.vehicles["Base.SC_FordMustang90"] = {index = -1, spawnChance = 5};
    VehicleZoneDistribution.trafficjamn.vehicles["Base.SC_FordMustang90_Undercover"] = {index = -1, spawnChance = 3};
    VehicleZoneDistribution.trafficjamn.vehicles["Base.SC_CadillacFleetwoodBrougham"] = {index = -1, spawnChance = 1};
    VehicleZoneDistribution.trafficjamn.vehicles["Base.SC_CadillacLimo"] = {index = -1, spawnChance = 1};
    VehicleZoneDistribution.trafficjamn.vehicles["Base.SC_ChevroletK5Blazer"] = {index = -1, spawnChance = 5};
    VehicleZoneDistribution.trafficjamn.vehicles["Base.SC_ChevroletK5BlazerFossoil"] = {index = -1, spawnChance = 1};
    VehicleZoneDistribution.trafficjamn.vehicles["Base.SC_ChevroletK5BlazerMcCoys"] = {index = -1, spawnChance = 1};
    VehicleZoneDistribution.trafficjamn.vehicles["Base.SC_ChevroletK5BlazerParkRanger"] = {index = -1, spawnChance = 0.5};
    VehicleZoneDistribution.trafficjamn.vehicles["Base.SC_ChevroletCaprice85"] = {index = -1, spawnChance = 15};
    VehicleZoneDistribution.trafficjamn.vehicles["Base.SC_ChevroletSuburban"] = {index = -1, spawnChance = 0.5};
    VehicleZoneDistribution.trafficjamn.vehicles["Base.SC_ChevroletCavalier"] = {index = -1, spawnChance = 5};
    VehicleZoneDistribution.trafficjamn.vehicles["Base.SC_ChevroletCamaro87"] = {index = -1, spawnChance = 1};
    VehicleZoneDistribution.trafficjamn.vehicles["Base.SC_ChevroletP30"] = {index = -1, spawnChance = 1};
    VehicleZoneDistribution.trafficjamn.vehicles["Base.SC_ChevroletP30_Mail"] = {index = -1, spawnChance = 0.5};
    VehicleZoneDistribution.trafficjamn.vehicles["Base.SC_ChevroletP30_Heralds"] = {index = -1, spawnChance = 0.5};
    VehicleZoneDistribution.trafficjamn.vehicles["Base.SC_ChevroletP30_Scarlet"] = {index = -1, spawnChance = 0.5};
    VehicleZoneDistribution.trafficjamn.vehicles["Base.SC_ChevroletP30_BunnyBread"] = {index = -1, spawnChance = 5};
    VehicleZoneDistribution.trafficjamn.vehicles["Base.SC_ChevroletP30_Greenes"] = {index = -1, spawnChance = 5};
    VehicleZoneDistribution.trafficjamn.vehicles["Base.SC_ChevroletG30"] = {index = -1, spawnChance = 10};
    VehicleZoneDistribution.trafficjamn.vehicles["Base.SC_ChevroletG30_Seats"] = {index = -1, spawnChance = 1};
    VehicleZoneDistribution.trafficjamn.vehicles["Base.SC_ChevroletG30_Mail"] = {index = -1, spawnChance = 5};
    VehicleZoneDistribution.trafficjamn.vehicles["Base.SC_ChevroletG30_McCoy"] = {index = -1, spawnChance = 5};
    VehicleZoneDistribution.trafficjamn.vehicles["Base.SC_ChevroletG30_Spiffo"] = {index = -1, spawnChance = 5};
    VehicleZoneDistribution.trafficjamn.vehicles["Base.SC_ChevroletG30_Fossoil"] = {index = -1, spawnChance = 5};
    VehicleZoneDistribution.trafficjamn.vehicles["Base.SC_ChevroletG30_LectroMax"] = {index = -1, spawnChance = 5};
    VehicleZoneDistribution.trafficjamn.vehicles["Base.SC_ChevroletG30_MassGenFac"] = {index = -1, spawnChance = 5};
    VehicleZoneDistribution.trafficjamn.vehicles["Base.SC_ChevroletG30_Ambulance"] = {index = -1, spawnChance = 5};
    VehicleZoneDistribution.trafficjamn.vehicles["Base.SC_ChevroletG30_SpecialForces"] = {index = -1, spawnChance = 3};
    VehicleZoneDistribution.trafficjamn.vehicles["Base.SC_ChevroletG30_BoxVan"] = {index = -1, spawnChance = 0.5};
    VehicleZoneDistribution.trafficjamn.vehicles["Base.SC_FordF700BoxTruck"] = {index = -1, spawnChance = 5};
    VehicleZoneDistribution.trafficjamn.vehicles["Base.SC_FordF700BoxTruck_DumpTruck"] = {index = -1, spawnChance = 3};
    VehicleZoneDistribution.trafficjamn.vehicles["Base.SC_FordF700BoxTruck_MacTools"] = {index = -1, spawnChance = 0.1};
    VehicleZoneDistribution.trafficjamn.vehicles["Base.SC_FordF700BoxTruck_GigaMart"] = {index = -1, spawnChance = 3};
    VehicleZoneDistribution.trafficjamn.vehicles["Base.SC_FordF700BoxTruck_Greenes"] = {index = -1, spawnChance = 3};
    VehicleZoneDistribution.trafficjamn.vehicles["Base.SC_FordF700BoxTruck_BunnyBread"] = {index = -1, spawnChance = 3};
    VehicleZoneDistribution.trafficjamn.vehicles["Base.SC_MackDM800Garbage"] = {index = -1, spawnChance = 5};
    VehicleZoneDistribution.trafficjamn.vehicles["Base.SC_ChevroletC70GrainTruck"] = {index = -1, spawnChance = 5};
    VehicleZoneDistribution.trafficjamn.vehicles["Base.SC_FordMustang90_JeffersonPolice"] = {index = -1, spawnChance = 3};
    VehicleZoneDistribution.trafficjamn.vehicles["Base.SC_FordMustang90_StatePolice"] = {index = -1, spawnChance = 3};
    VehicleZoneDistribution.trafficjamn.vehicles["Base.SC_FordCrownVictoria85"] = {index = -1, spawnChance = 3};
    VehicleZoneDistribution.trafficjamn.vehicles["Base.SC_FordCrownVictoria85_LouisvillePolice"] = {index = -1, spawnChance = 30};
    VehicleZoneDistribution.trafficjamn.vehicles["Base.SC_FordCrownVictoria92_JeffersonSheriff"] = {index = -1, spawnChance = 30};
    VehicleZoneDistribution.trafficjamn.vehicles["Base.SC_ToyotaCamry"] = {index = -1, spawnChance = 10};
    VehicleZoneDistribution.trafficjamn.vehicles["Base.SC_Porsche911"] = {index = -1, spawnChance = 5};
    VehicleZoneDistribution.trafficjamn.vehicles["Base.SC_Mercedes280"] = {index = -1, spawnChance = 10};
    VehicleZoneDistribution.trafficjamn.vehicles["Base.SC_HahnPumperRed"] = {index = -1, spawnChance = 0.5};
    VehicleZoneDistribution.trafficjamn.vehicles["Base.SC_HahnPumperYellow"] = {index = -1, spawnChance = 0.5};
    VehicleZoneDistribution.trafficjamn.vehicles["Base.SC_CrownFirecoachRed"] = {index = -1, spawnChance = 0.5};
    VehicleZoneDistribution.trafficjamn.vehicles["Base.SC_CrownFirecoachWhite"] = {index = -1, spawnChance = 0.5};
    VehicleZoneDistribution.trafficjamn.vehicles["Base.SC_SmallUtilityTrailer"] = {index = -1, spawnChance = 10};
    VehicleZoneDistribution.trafficjamn.vehicles["Base.SC_MediumEnclosedTrailer"] = {index = -1, spawnChance = 10};
    VehicleZoneDistribution.trafficjamn.vehicles["Base.SC_MediumLivestockTrailer"] = {index = -1, spawnChance = 10};
    VehicleZoneDistribution.trafficjamn.vehicles["Base.SC_M1101Trailer"] = {index = -1, spawnChance = 10};
    VehicleZoneDistribution.trafficjamn.chanceToPartDamage = 10;
    VehicleZoneDistribution.trafficjamn.baseVehicleQuality = 1.1;
	VehicleZoneDistribution.trafficjamn.chanceToSpawnKey = 80;

    VehicleZoneDistribution.trafficjams.vehicles["Base.SC_AMGeneralM35A2"] = {index = -1, spawnChance = 50};

    VehicleZoneDistribution.trafficjams.vehicles["Base.SC_AMGeneralM998Soft_3Tone"] = {index = -1, spawnChance = 50};
    VehicleZoneDistribution.trafficjams.vehicles["Base.SC_AMGeneralM998Soft_OD"] = {index = -1, spawnChance = 10};
    VehicleZoneDistribution.trafficjams.vehicles["Base.SC_AMGeneralM998Soft_Tan"] = {index = -1, spawnChance = 5};
    VehicleZoneDistribution.trafficjams.vehicles["Base.SC_AMGeneralM1025_AllCamos"] = {index = -1, spawnChance = 50};
    VehicleZoneDistribution.trafficjams.vehicles["Base.SC_AMGeneralM1025MP_AllCamos"] = {index = -1, spawnChance = 10};

    VehicleZoneDistribution.trafficjams.vehicles["Base.SC_AMGeneralM1097"] = {index = -1, spawnChance = 50};
    VehicleZoneDistribution.trafficjams.vehicles["Base.SC_AMGeneralM1097TroopCarrier"] = {index = -1, spawnChance = 50};
    VehicleZoneDistribution.trafficjams.vehicles["Base.SC_AMGeneralM1097TroopCarrierTan"] = {index = -1, spawnChance = 10};

    VehicleZoneDistribution.trafficjams.vehicles["Base.SC_AMGeneralM997"] = {index = -1, spawnChance = 10};
    VehicleZoneDistribution.trafficjams.vehicles["Base.SC_AMGeneralM997Green"] = {index = -1, spawnChance = 10};

    VehicleZoneDistribution.trafficjams.vehicles["Base.SC_FordExplorer"] = {index = -1, spawnChance = 5};
    VehicleZoneDistribution.trafficjams.vehicles["Base.SC_FordTaurus"] = {index = -1, spawnChance = 15};
    VehicleZoneDistribution.trafficjams.vehicles["Base.SC_HondaAccord"] = {index = -1, spawnChance = 15};
    VehicleZoneDistribution.trafficjams.vehicles["Base.SC_VWRabbit"] = {index = -1, spawnChance = 15};
    VehicleZoneDistribution.trafficjams.vehicles["Base.SC_MazdaB2000"] = {index = -1, spawnChance = 10};
    VehicleZoneDistribution.trafficjams.vehicles["Base.SC_FordCrownVictoria85"] = {index = -1, spawnChance = 10};
    VehicleZoneDistribution.trafficjams.vehicles["Base.SC_FordCrownVictoria85_Taxi"] = {index = -1, spawnChance = 1};
    VehicleZoneDistribution.trafficjams.vehicles["Base.SC_FordCrownVictoria85_StatePolice"] = {index = -1, spawnChance = 1};
    VehicleZoneDistribution.trafficjams.vehicles["Base.SC_FordCrownVictoria85_ParkRanger"] = {index = -1, spawnChance = 1};
    VehicleZoneDistribution.trafficjams.vehicles["Base.SC_FordF350Ambulance"] = {index = -1, spawnChance = 10};
    VehicleZoneDistribution.trafficjams.vehicles["Base.SC_GrummanLLV"] = {index = -1, spawnChance = 5};
    VehicleZoneDistribution.trafficjams.vehicles["Base.SC_JeepCJ7"] = {index = -1, spawnChance = 5};
    VehicleZoneDistribution.trafficjams.vehicles["Base.SC_JeepCherokee"] = {index = -1, spawnChance = 5};
    VehicleZoneDistribution.trafficjams.vehicles["Base.SC_PlymouthVoyager"] = {index = -1, spawnChance = 10};
    VehicleZoneDistribution.trafficjams.vehicles["Base.SC_VWRabbit_Pizza"] = {index = -1, spawnChance = 5};
    VehicleZoneDistribution.trafficjams.vehicles["Base.SC_GeoTracker"] = {index = -1, spawnChance = 10};
    VehicleZoneDistribution.trafficjams.vehicles["Base.SC_FordBronco"] = {index = -1, spawnChance = 6};
    VehicleZoneDistribution.trafficjams.vehicles["Base.SC_FordF15092"] = {index = -1, spawnChance = 5};
    VehicleZoneDistribution.trafficjams.vehicles["Base.SC_FordMustang90"] = {index = -1, spawnChance = 5};
    VehicleZoneDistribution.trafficjams.vehicles["Base.SC_FordMustang90_Undercover"] = {index = -1, spawnChance = 3};
    VehicleZoneDistribution.trafficjams.vehicles["Base.SC_ChevroletK5Blazer"] = {index = -1, spawnChance = 5};
    VehicleZoneDistribution.trafficjams.vehicles["Base.SC_ChevroletK5BlazerFossoil"] = {index = -1, spawnChance = 1};
    VehicleZoneDistribution.trafficjams.vehicles["Base.SC_ChevroletK5BlazerMcCoys"] = {index = -1, spawnChance = 1};
    VehicleZoneDistribution.trafficjams.vehicles["Base.SC_ChevroletK5BlazerParkRanger"] = {index = -1, spawnChance = 0.5};
    VehicleZoneDistribution.trafficjams.vehicles["Base.SC_ChevroletCaprice85"] = {index = -1, spawnChance = 15};
    VehicleZoneDistribution.trafficjams.vehicles["Base.SC_ChevroletSuburban"] = {index = -1, spawnChance = 0.5};
    VehicleZoneDistribution.trafficjams.vehicles["Base.SC_ChevroletCavalier"] = {index = -1, spawnChance = 5};
    VehicleZoneDistribution.trafficjams.vehicles["Base.SC_ChevroletCamaro87"] = {index = -1, spawnChance = 1};
    VehicleZoneDistribution.trafficjams.vehicles["Base.SC_ChevroletP30_"] = {index = -1, spawnChance = 1};
    VehicleZoneDistribution.trafficjams.vehicles["Base.SC_ChevroletP30_Mail"] = {index = -1, spawnChance = 0.5};
    VehicleZoneDistribution.trafficjams.vehicles["Base.SC_ChevroletP30_Heralds"] = {index = -1, spawnChance = 0.5};
    VehicleZoneDistribution.trafficjams.vehicles["Base.SC_ChevroletP30_Scarlet"] = {index = -1, spawnChance = 0.5};
    VehicleZoneDistribution.trafficjams.vehicles["Base.SC_ChevroletP30_BunnyBread"] = {index = -1, spawnChance = 5};
    VehicleZoneDistribution.trafficjams.vehicles["Base.SC_ChevroletP30_Greenes"] = {index = -1, spawnChance = 5};
    VehicleZoneDistribution.trafficjams.vehicles["Base.SC_ChevroletG30"] = {index = -1, spawnChance = 10};
    VehicleZoneDistribution.trafficjams.vehicles["Base.SC_ChevroletG30Seats"] = {index = -1, spawnChance = 1};
    VehicleZoneDistribution.trafficjams.vehicles["Base.SC_ChevroletG30_Mail"] = {index = -1, spawnChance = 5};
    VehicleZoneDistribution.trafficjams.vehicles["Base.SC_ChevroletG30_McCoy"] = {index = -1, spawnChance = 5};
    VehicleZoneDistribution.trafficjams.vehicles["Base.SC_ChevroletG30_Spiffo"] = {index = -1, spawnChance = 5};
    VehicleZoneDistribution.trafficjams.vehicles["Base.SC_ChevroletG30_Fossoil"] = {index = -1, spawnChance = 5};
    VehicleZoneDistribution.trafficjams.vehicles["Base.SC_ChevroletG30_LectroMax"] = {index = -1, spawnChance = 5};
    VehicleZoneDistribution.trafficjams.vehicles["Base.SC_ChevroletG30_MassGenFac"] = {index = -1, spawnChance = 5};
    VehicleZoneDistribution.trafficjams.vehicles["Base.SC_ChevroletG30_Ambulance"] = {index = -1, spawnChance = 5};
    VehicleZoneDistribution.trafficjams.vehicles["Base.SC_ChevroletG30_SpecialForces"] = {index = -1, spawnChance = 3};
    VehicleZoneDistribution.trafficjams.vehicles["Base.SC_ChevroletG30_BoxVan"] = {index = -1, spawnChance = 0.5};
    VehicleZoneDistribution.trafficjams.vehicles["Base.SC_FordF700BoxTruck"] = {index = -1, spawnChance = 5};
    VehicleZoneDistribution.trafficjams.vehicles["Base.SC_FordF700BoxTruck_DumpTruck"] = {index = -1, spawnChance = 3};
    VehicleZoneDistribution.trafficjams.vehicles["Base.SC_FordF700BoxTruck_MacTools"] = {index = -1, spawnChance = 0.1};
    VehicleZoneDistribution.trafficjams.vehicles["Base.SC_FordF700BoxTruck_GigaMart"] = {index = -1, spawnChance = 3};
    VehicleZoneDistribution.trafficjams.vehicles["Base.SC_FordF700BoxTruck_Greenes"] = {index = -1, spawnChance = 3};
    VehicleZoneDistribution.trafficjams.vehicles["Base.SC_FordF700BoxTruck_BunnyBread"] = {index = -1, spawnChance = 3};
    VehicleZoneDistribution.trafficjams.vehicles["Base.SC_MackDM800Garbage"] = {index = -1, spawnChance = 5};
    VehicleZoneDistribution.trafficjams.vehicles["Base.SC_ChevroletC70GrainTruck"] = {index = -1, spawnChance = 5};
    VehicleZoneDistribution.trafficjams.vehicles["Base.SC_FordMustang90_JeffersonPolice"] = {index = -1, spawnChance = 3};
    VehicleZoneDistribution.trafficjams.vehicles["Base.SC_FordMustang90_StatePolice"] = {index = -1, spawnChance = 3};
    VehicleZoneDistribution.trafficjams.vehicles["Base.SC_FordCrownVictoria85"] = {index = -1, spawnChance = 3};
    VehicleZoneDistribution.trafficjams.vehicles["Base.SC_FordCrownVictoria85_LouisvillePolice"] = {index = -1, spawnChance = 3};
    VehicleZoneDistribution.trafficjams.vehicles["Base.SC_FordCrownVictoria92_JeffersonSheriff"] = {index = -1, spawnChance = 3};
    VehicleZoneDistribution.trafficjams.vehicles["Base.SC_ToyotaCamry"] = {index = -1, spawnChance = 10};
    VehicleZoneDistribution.trafficjams.vehicles["Base.SC_SmallUtilityTrailer"] = {index = -1, spawnChance = 10};
    VehicleZoneDistribution.trafficjams.vehicles["Base.SC_MediumEnclosedTrailer"] = {index = -1, spawnChance = 10};
    VehicleZoneDistribution.trafficjams.vehicles["Base.SC_MediumLivestockTrailer"] = {index = -1, spawnChance = 10};
    VehicleZoneDistribution.trafficjams.vehicles["Base.SC_M1101Trailer"] = {index = -1, spawnChance = 10};
    VehicleZoneDistribution.trafficjams.chanceToPartDamage = 10;
    VehicleZoneDistribution.trafficjams.baseVehicleQuality = 1.1;
	VehicleZoneDistribution.trafficjams.chanceToSpawnKey = 80;

end