if VehicleZoneDistribution then

    VehicleZoneDistribution.parkingstall.vehicles["Base.SC_FordGalaxie"] = {index = -1, spawnChance = 0.5};
    VehicleZoneDistribution.parkingstall.vehicles["Base.SC_FordExplorer"] = {index = -1, spawnChance = 5};
    VehicleZoneDistribution.parkingstall.vehicles["Base.SC_FordTaurus"] = {index = -1, spawnChance = 15};
    VehicleZoneDistribution.parkingstall.vehicles["Base.SC_HondaAccord"] = {index = -1, spawnChance = 15};
    VehicleZoneDistribution.parkingstall.vehicles["Base.SC_VWRabbit"] = {index = -1, spawnChance = 15};
    VehicleZoneDistribution.parkingstall.vehicles["Base.SC_MazdaB2000"] = {index = -1, spawnChance = 15};
    VehicleZoneDistribution.parkingstall.vehicles["Base.SC_FordCrownVictoria85"] = {index = -1, spawnChance = 10};
    VehicleZoneDistribution.parkingstall.vehicles["Base.SC_FordCrownVictoria85TaxI"] = {index = -1, spawnChance = 1};
    VehicleZoneDistribution.parkingstall.vehicles["Base.SC_FordCrownVictoria85StatePolice"] = {index = -1, spawnChance = 1};
    VehicleZoneDistribution.parkingstall.vehicles["Base.SC_FordCrownVictoria85ParkRanger"] = {index = -1, spawnChance = 0.2};
    VehicleZoneDistribution.parkingstall.vehicles["Base.SC_FordCrownVictoria92"] = {index = -1, spawnChance = 1};
    VehicleZoneDistribution.parkingstall.vehicles["Base.SC_FordF350Ambulance"] = {index = -1, spawnChance = 0.001};
    VehicleZoneDistribution.parkingstall.vehicles["Base.SC_GrummanLLV"] = {index = -1, spawnChance = 0.02};
    VehicleZoneDistribution.parkingstall.vehicles["Base.SC_FordF700ArmoredBank"] = {index = -1, spawnChance = 0.01};
    VehicleZoneDistribution.parkingstall.vehicles["Base.SC_JeepCJ7"] = {index = -1, spawnChance = 1};
    VehicleZoneDistribution.parkingstall.vehicles["Base.SC_JeepCherokee"] = {index = -1, spawnChance = 0.8};
    VehicleZoneDistribution.parkingstall.vehicles["Base.SC_PlymouthVoyager"] = {index = -1, spawnChance = 0.5};
    VehicleZoneDistribution.parkingstall.vehicles["Base.SC_VWRabbitPizza"] = {index = -1, spawnChance = 1};
    VehicleZoneDistribution.parkingstall.vehicles["Base.SC_GeoTracker"] = {index = -1, spawnChance = 5};
    VehicleZoneDistribution.parkingstall.vehicles["Base.SC_FordBronco"] = {index = -1, spawnChance = 5};
    VehicleZoneDistribution.parkingstall.vehicles["Base.SC_FordF150"] = {index = -1, spawnChance = 5};
    VehicleZoneDistribution.parkingstall.vehicles["Base.SC_FordMustang90"] = {index = -1, spawnChance = 5};
    VehicleZoneDistribution.parkingstall.vehicles["Base.SC_FordMustang90StatePolice"] = {index = -1, spawnChance = 0.5};
    VehicleZoneDistribution.parkingstall.vehicles["Base.SC_FordMustang90Undercover"] = {index = -1, spawnChance = 0.2};
    VehicleZoneDistribution.parkingstall.vehicles["Base.SC_ChevroletK5Blazer"] = {index = -1, spawnChance = 5};
    VehicleZoneDistribution.parkingstall.vehicles["Base.SC_ChevroletK5BlazerFossoil"] = {index = -1, spawnChance = 1};
    VehicleZoneDistribution.parkingstall.vehicles["Base.SC_ChevroletK5BlazerMcCoys"] = {index = -1, spawnChance = 1};
    VehicleZoneDistribution.parkingstall.vehicles["Base.SC_ChevroletK5BlazerParkRanger"] = {index = -1, spawnChance = 0.5};
    VehicleZoneDistribution.parkingstall.vehicles["Base.SC_ChevroletCaprice85"] = {index = -1, spawnChance = 15};
    VehicleZoneDistribution.parkingstall.vehicles["Base.SC_ChevroletSuburban"] = {index = -1, spawnChance = 0.5};
    VehicleZoneDistribution.parkingstall.vehicles["Base.SC_ChevroletCavalier"] = {index = -1, spawnChance = 15};
    VehicleZoneDistribution.parkingstall.vehicles["Base.SC_ChevroletCamaro87"] = {index = -1, spawnChance = 1};
    VehicleZoneDistribution.parkingstall.vehicles["Base.SC_ChevroletP30"] = {index = -1, spawnChance = 1};
    VehicleZoneDistribution.parkingstall.vehicles["Base.SC_ChevroletP30Mail"] = {index = -1, spawnChance = 0.1};
    VehicleZoneDistribution.parkingstall.vehicles["Base.SC_ChevroletP30Heralds"] = {index = -1, spawnChance = 0.1};
    VehicleZoneDistribution.parkingstall.vehicles["Base.SC_ChevroletP30Scarlet"] = {index = -1, spawnChance = 0.1};
    VehicleZoneDistribution.parkingstall.vehicles["Base.SC_ChevroletP30BunnyBread"] = {index = -1, spawnChance = 0.3};
    VehicleZoneDistribution.parkingstall.vehicles["Base.SC_ChevroletP30Greenes"] = {index = -1, spawnChance = 0.3};
    VehicleZoneDistribution.parkingstall.vehicles["Base.SC_ChevroletG30"] = {index = -1, spawnChance = 1};
    VehicleZoneDistribution.parkingstall.vehicles["Base.SC_ChevroletG30Seats"] = {index = -1, spawnChance = 1};
    VehicleZoneDistribution.parkingstall.vehicles["Base.SC_ChevroletG30Mail"] = {index = -1, spawnChance = 1};
    VehicleZoneDistribution.parkingstall.vehicles["Base.SC_ChevroletG30McCoy"] = {index = -1, spawnChance = 1};
    VehicleZoneDistribution.parkingstall.vehicles["Base.SC_ChevroletG30Spiffo"] = {index = -1, spawnChance = 1};
    VehicleZoneDistribution.parkingstall.vehicles["Base.SC_ChevroletG30Fossoil"] = {index = -1, spawnChance = 1};
    VehicleZoneDistribution.parkingstall.vehicles["Base.SC_ChevroletG30LectroMax"] = {index = -1, spawnChance = 1};
    VehicleZoneDistribution.parkingstall.vehicles["Base.SC_ChevroletG30MassGenFac"] = {index = -1, spawnChance = 1};
    VehicleZoneDistribution.parkingstall.vehicles["Base.SC_ChevroletG30Ambulance"] = {index = -1, spawnChance = 0.001};
    VehicleZoneDistribution.parkingstall.vehicles["Base.SC_ChevroletG30SpecialForces"] = {index = -1, spawnChance = 0.1};
    VehicleZoneDistribution.parkingstall.vehicles["Base.SC_ChevroletG30BoxVan"] = {index = -1, spawnChance = 0.5};
    VehicleZoneDistribution.parkingstall.vehicles["Base.SC_FordF700BoxTruck"] = {index = -1, spawnChance = 0.5};
    VehicleZoneDistribution.parkingstall.vehicles["Base.SC_FordF700DumpTruck"] = {index = -1, spawnChance = 0.5};
    VehicleZoneDistribution.parkingstall.vehicles["Base.SC_FordF700MacTools"] = {index = -1, spawnChance = 0.5};       
    VehicleZoneDistribution.parkingstall.vehicles["Base.SC_FordF700GigaMart"] = {index = -1, spawnChance = 0.5};     
    VehicleZoneDistribution.parkingstall.vehicles["Base.SC_FordF700Greenes"] = {index = -1, spawnChance = 0.5};
    VehicleZoneDistribution.parkingstall.vehicles["Base.SC_FordF700BunnyBread"] = {index = -1, spawnChance = 0.5};       
    VehicleZoneDistribution.parkingstall.vehicles["Base.SC_MackDM800Garbage"] = {index = -1, spawnChance = 0.2};       
    VehicleZoneDistribution.parkingstall.chanceToPartDamage = 10;
    
    VehicleZoneDistribution.spiffo.vehicles["Base.SC_ChevroletG30Spiffo"] = {index = -1, spawnChance = 1};  
    VehicleZoneDistribution.spiffo.chanceToPartDamage = 5;

    VehicleZoneDistribution.medium.vehicles["Base.SC_ChevroletP30Greenes"] = {index = -1, spawnChance = 1};
    VehicleZoneDistribution.medium.vehicles["Base.SC_ChevroletP30BunnyBread"] = {index = -1, spawnChance = 1};
    VehicleZoneDistribution.medium.vehicles["Base.SC_FordF700BoxTruck"] = {index = -1, spawnChance = 5};
    VehicleZoneDistribution.medium.vehicles["Base.SC_FordF700PanelTruck"] = {index = -1, spawnChance = 5};
    VehicleZoneDistribution.medium.vehicles["Base.SC_FordF700DumpTruck"] = {index = -1, spawnChance = 5};
    VehicleZoneDistribution.medium.vehicles["Base.SC_ChevroletCaprice85"] = {index = -1, spawnChance = 15};
    VehicleZoneDistribution.medium.chanceToPartDamage = 10;
    
    VehicleZoneDistribution.good.vehicles["Base.SC_ChevroletP30Greenes"] = {index = -1, spawnChance = 0.5};
    VehicleZoneDistribution.good.vehicles["Base.SC_ChevroletP30BunnyBread"] = {index = -1, spawnChance = 0.5};
    VehicleZoneDistribution.good.vehicles["Base.SC_ChevroletCaprice85"] = {index = -1, spawnChance = 35};
    VehicleZoneDistribution.good.vehicles["Base.SC_JeepCherokee"] = {index = -1, spawnChance = 35};
    VehicleZoneDistribution.good.vehicles["Base.SC_MazdaB2000"] = {index = -1, spawnChance = 35};
    VehicleZoneDistribution.good.vehicles["Base.SC_GeoTracker"] = {index = -1, spawnChance = 35};
    VehicleZoneDistribution.good.vehicles["Base.SC_FordF150"] = {index = -1, spawnChance = 35};
    VehicleZoneDistribution.good.vehicles["Base.SC_FordBronco"] = {index = -1, spawnChance = 35};
    VehicleZoneDistribution.good.vehicles["Base.SC_PlymouthVoyager"] = {index = -1, spawnChance = 30};
    VehicleZoneDistribution.good.vehicles["Base.SC_Porsche911G50"] = {index = -1, spawnChance = 5};
    VehicleZoneDistribution.good.vehicles["Base.SC_FordMustang90"] = {index = -1, spawnChance = 25};
    VehicleZoneDistribution.good.vehicles["Base.SC_CadillacBrougham"] = {index = -1, spawnChance = 5};
    VehicleZoneDistribution.good.vehicles["Base.SC_Mercedes280"] = {index = -1, spawnChance = 5};
    VehicleZoneDistribution.good.vehicles["Base.SC_BMW520i"] = {index = -1, spawnChance = 5};
    VehicleZoneDistribution.good.vehicles["Base.SC_FordTaurus"] = {index = -1, spawnChance = 25};
    VehicleZoneDistribution.good.vehicles["Base.SC_ChevroletCavalier"] = {index = -1, spawnChance = 25};
    VehicleZoneDistribution.good.chanceToPartDamage = 5;
    VehicleZoneDistribution.good.baseVehicleQuality = 1.1;
    VehicleZoneDistribution.good.chanceToPartDamage = 5;

    VehicleZoneDistribution.sport.vehicles["Base.SC_FordMustang90"] = {index = -1, spawnChance = 70};
    VehicleZoneDistribution.sport.vehicles["Base.SC_FordBronco"] = {index = -1, spawnChance = 70};
    VehicleZoneDistribution.sport.vehicles["Base.SC_Porsche911G50"] = {index = -1, spawnChance = 10};
    VehicleZoneDistribution.sport.vehicles["Base.SC_JeepCherokee"] = {index = -1, spawnChance = 70};
    VehicleZoneDistribution.sport.vehicles["Base.SC_BMW520i"] = {index = -1, spawnChance = 50};
    VehicleZoneDistribution.sport.vehicles["Base.SC_CadillacBrougham"] = {index = -1, spawnChance = 80};
    VehicleZoneDistribution.sport.vehicles["Base.SC_ChevroletSuburban"] = {index = -1, spawnChance = 50};
    VehicleZoneDistribution.sport.vehicles["Base.SC_ChevroletCamaro87"] = {index = -1, spawnChance = 50};

    VehicleZoneDistribution.police.vehicles["Base.SC_ChevroletP30SWAT"] = {index = -1, spawnChance = 1};
    VehicleZoneDistribution.police.vehicles["Base.SC_ChevroletSuburbanStatePolice"] = {index = -1, spawnChance = 15};
    VehicleZoneDistribution.police.vehicles["Base.SC_FordMustang90JeffersonPolice"] = {index = -1, spawnChance = 30};
    VehicleZoneDistribution.police.vehicles["Base.SC_FordMustang90StatePolice"] = {index = -1, spawnChance = 30};
    VehicleZoneDistribution.police.vehicles["Base.SC_FordMustang90Undercover"] = {index = -1, spawnChance = 30};
    VehicleZoneDistribution.police.vehicles["Base.SC_FordCrownVictoria85StatePolice"] = {index = -1, spawnChance = 50};
    VehicleZoneDistribution.police.vehicles["Base.SC_FordCrownVictoria92Jefferson"] = {index = -1, spawnChance = 30};
    VehicleZoneDistribution.police.vehicles["Base.SC_FordCrownVictoria92Muhlen"] = {index = -1, spawnChance = 30};
    VehicleZoneDistribution.police.vehicles["Base.SC_FordCrownVictoria92Warren"] = {index = -1, spawnChance = 30};
    VehicleZoneDistribution.police.vehicles["Base.SC_FordCrownVictoria92Meade"] = {index = -1, spawnChance = 30};
    VehicleZoneDistribution.police.vehicles["Base.SC_FordF700ArmoredPolice"] = {index = -1, spawnChance = 1};
    VehicleZoneDistribution.police.baseVehicleQuality = 1.1;
    VehicleZoneDistribution.police.chanceToPartDamage = 5;

    VehicleZoneDistribution.postal.vehicles["Base.SC_GrummanLLV"] = {index = -1, spawnChance = 100};
    VehicleZoneDistribution.postal.vehicles["Base.SC_ChevroletP30Mail"] = {index = -1, spawnChance = 25};
    VehicleZoneDistribution.postal.vehicles["Base.SC_ChevroletG30Mail"] = {index = -1, spawnChance = 25};
    VehicleZoneDistribution.postal.chanceToPartDamage = 5;

    VehicleZoneDistribution.mccoy.vehicles["Base.SC_FordF700BoxTruck"] = {index = -1, spawnChance = 25};
    VehicleZoneDistribution.mccoy.vehicles["Base.SC_FordF700MacTools"] = {index = -1, spawnChance = 25};
    VehicleZoneDistribution.mccoy.vehicles["Base.SC_FordF700PanelTruck"] = {index = -1, spawnChance = 25};
    VehicleZoneDistribution.mccoy.vehicles["Base.SC_FordF700DumpTruck"] = {index = -1, spawnChance = 25};
    VehicleZoneDistribution.mccoy.vehicles["Base.SC_ChevroletG30McCoy"] = {index = -1, spawnChance = 25};
    VehicleZoneDistribution.mccoy.vehicles["Base.SC_ChevroletG30BoxVan"] = {index = -1, spawnChance = 25};
    VehicleZoneDistribution.mccoy.vehicles["Base.SC_ChevroletK5BlazerMcCoys"] = {index = -1, spawnChance = 25};
    VehicleZoneDistribution.mccoy.vehicles["Base.SC_ChevroletK5BlazerFossoil"] = {index = -1, spawnChance = 25};
    VehicleZoneDistribution.mccoy.chanceToPartDamage = 25;
    
    VehicleZoneDistribution.knoxdisti.vehicles["Base.SC_ChevroletP30Disti"] = {index = -1, spawnChance = 30};
    VehicleZoneDistribution.knoxdisti.vehicles["Base.SC_FordCrownVictoria85LouisvillePolice"] = {index = -1, spawnChance = 5};
    VehicleZoneDistribution.knoxdisti.vehicles["Base.SC_FordCrownVictoria92LouisvillePolice"] = {index = -1, spawnChance = 5};
    VehicleZoneDistribution.knoxdisti.vehicles["Base.SC_FordCrownVictoria92JeffersonPolice"] = {index = -1, spawnChance = 5};
    VehicleZoneDistribution.knoxdisti.vehicles["Base.SC_JeepCherokeeAudubon"] = {index = -1, spawnChance = 10};
    VehicleZoneDistribution.knoxdisti.chanceToPartDamage = 5;

    VehicleZoneDistribution.massgenfac.vehicles["Base.SC_ChevroletG30MassGenFac"] = {index = -1, spawnChance = 30};
    VehicleZoneDistribution.massgenfac.vehicles["Base.SC_FordMustang90JeffersonPolice"] = {index = -1, spawnChance = 5};
    VehicleZoneDistribution.massgenfac.vehicles["Base.SC_FordCrownVictoria85LouisvillePolice"] = {index = -1, spawnChance = 5};
    VehicleZoneDistribution.massgenfac.vehicles["Base.SC_FordCrownVictoria92LouisvillePolice"] = {index = -1, spawnChance = 5};
    VehicleZoneDistribution.massgenfac.vehicles["Base.SC_JeepCherokeeAudubon"] = {index = -1, spawnChance = 5};
    VehicleZoneDistribution.massgenfac.vehicles["Base.SC_ChevroletG30BoxVan"] = {index = -1, spawnChance = 25};
    VehicleZoneDistribution.massgenfac.chanceToPartDamage = 10;

    VehicleZoneDistribution.network3.vehicles["Base.SC_FordMustang90JeffersonPolice"] = {index = -1, spawnChance = 5};
    VehicleZoneDistribution.network3.vehicles["Base.SC_FordCrownVictoria85LouisvillePolice"] = {index = -1, spawnChance = 5};
    VehicleZoneDistribution.network3.vehicles["Base.SC_FordCrownVictoria92LouisvillePolice"] = {index = -1, spawnChance = 5};
    VehicleZoneDistribution.network3.vehicles["Base.SC_JeepCherokeeAudubon"] = {index = -1, spawnChance = 10};
    VehicleZoneDistribution.network3.chanceToPartDamage = 5;

    VehicleZoneDistribution.kyheralds.vehicles["Base.SC_ChevroletP30Heralds"] = {index = -1, spawnChance = 30};
    VehicleZoneDistribution.kyheralds.vehicles["Base.SC_FordMustang90JeffersonPolice"] = {index = -1, spawnChance = 5};
    VehicleZoneDistribution.kyheralds.vehicles["Base.SC_FordCrownVictoria85LouisvillePolice"] = {index = -1, spawnChance = 5};
    VehicleZoneDistribution.kyheralds.vehicles["Base.SC_FordCrownVictoria92LouisvillePolice"] = {index = -1, spawnChance = 5};
    VehicleZoneDistribution.kyheralds.vehicles["Base.SC_JeepCherokeeAudubon"] = {index = -1, spawnChance = 10};
    VehicleZoneDistribution.kyheralds.chanceToPartDamage = 5;

    VehicleZoneDistribution.junkyard.vehicles["Base.SC_FordF700PanelTruck"] = {index = -1, spawnChance = 5};  
    VehicleZoneDistribution.junkyard.vehicles["Base.SC_FordF700BoxTruck"] = {index = -1, spawnChance = 5};  
    VehicleZoneDistribution.junkyard.vehicles["Base.SC_FordF700DumpTruck"] = {index = -1, spawnChance = 5};  
    VehicleZoneDistribution.junkyard.vehicles["Base.SC_ChevroletG30SpecialForces"] = {index = -1, spawnChance = 5};  
    VehicleZoneDistribution.junkyard.chanceToPartDamage = 60;
    
    VehicleZoneDistribution.trafficjamn.vehicles["Base.SC_DodgeM880"] = {index = -1, spawnChance = 10};
    VehicleZoneDistribution.trafficjamn.vehicles["Base.SC_AMGeneralM151A2"] = {index = -1, spawnChance = 5};
    VehicleZoneDistribution.trafficjamn.vehicles["Base.SC_AMGeneralM151A2Tan"] = {index = -1, spawnChance = 1};
    VehicleZoneDistribution.trafficjamn.vehicles["Base.SC_AMGeneralM35A1"] = {index = -1, spawnChance = 50};
    VehicleZoneDistribution.trafficjamn.vehicles["Base.SC_AMGeneralM998"] = {index = -1, spawnChance = 50};
    VehicleZoneDistribution.trafficjamn.vehicles["Base.SC_AMGeneralM998Tan"] = {index = -1, spawnChance = 2};
    VehicleZoneDistribution.trafficjamn.vehicles["Base.SC_AMGeneralM998HardTop"] = {index = -1, spawnChance = 50};
    VehicleZoneDistribution.trafficjamn.vehicles["Base.SC_AMGeneralM998HardTopTan"] = {index = -1, spawnChance = 2};
    VehicleZoneDistribution.trafficjamn.vehicles["Base.SC_ChevroletM1008"] = {index = -1, spawnChance = 10};
    VehicleZoneDistribution.trafficjamn.vehicles["Base.SC_ChevroletM1008TroopCarrier"] = {index = -1, spawnChance = 10};
    VehicleZoneDistribution.trafficjamn.vehicles["Base.SC_ChevroletM1009"] = {index = -1, spawnChance = 10};
    VehicleZoneDistribution.trafficjamn.vehicles["Base.SC_AMGeneralM1025"] = {index = -1, spawnChance = 10};
    VehicleZoneDistribution.trafficjamn.vehicles["Base.SC_AMGeneralM1025Tan"] = {index = -1, spawnChance = 10};
    VehicleZoneDistribution.trafficjamn.vehicles["Base.SC_AMGeneralM1025MP"] = {index = -1, spawnChance = 5};
    VehicleZoneDistribution.trafficjamn.vehicles["Base.SC_AMGeneralM1025MPTan"] = {index = -1, spawnChance = 5};
    VehicleZoneDistribution.trafficjamn.vehicles["Base.SC_M35A1Crashed"] = {index = -1, spawnChance = 1};
    VehicleZoneDistribution.trafficjamn.vehicles["Base.SC_M35A1CrashedTurned"] = {index = -1, spawnChance = 5};
    VehicleZoneDistribution.trafficjamn.chanceToPartDamage = 10;
    VehicleZoneDistribution.trafficjamn.baseVehicleQuality = 1.1;
	VehicleZoneDistribution.trafficjamn.chanceToSpawnKey = 80;

    VehicleZoneDistribution.trafficjame.vehicles["Base.SC_DodgeM880"] = {index = -1, spawnChance = 5};
    VehicleZoneDistribution.trafficjame.vehicles["Base.SC_ChevroletM1008"] = {index = -1, spawnChance = 50};
    VehicleZoneDistribution.trafficjame.vehicles["Base.SC_ChevroletM1009"] = {index = -1, spawnChance = 50};
    VehicleZoneDistribution.trafficjame.vehicles["Base.SC_ChevroletM1010"] = {index = -1, spawnChance = 30};
    VehicleZoneDistribution.trafficjame.vehicles["Base.SC_AMGeneralM35A1"] = {index = -1, spawnChance = 10};
    VehicleZoneDistribution.trafficjame.vehicles["Base.SC_AMGeneralM998"] = {index = -1, spawnChance = 50};
    VehicleZoneDistribution.trafficjame.vehicles["Base.SC_AMGeneralM1025"] = {index = -1, spawnChance = 10};
    VehicleZoneDistribution.trafficjame.vehicles["Base.SC_AMGeneralM1025MP"] = {index = -1, spawnChance = 5};
    VehicleZoneDistribution.trafficjame.vehicles["Base.SC_AMGeneralM1025MPTan"] = {index = -1, spawnChance = 5};
    VehicleZoneDistribution.trafficjame.chanceToPartDamage = 10;
    VehicleZoneDistribution.trafficjame.baseVehicleQuality = 1.1;
	VehicleZoneDistribution.trafficjame.chanceToSpawnKey = 80;

    VehicleZoneDistribution.trafficjams.vehicles["Base.SC_DodgeM880"] = {index = -1, spawnChance = 5};
    VehicleZoneDistribution.trafficjams.vehicles["Base.SC_ChevroletM1008"] = {index = -1, spawnChance = 50};
    VehicleZoneDistribution.trafficjams.vehicles["Base.SC_ChevroletM1009"] = {index = -1, spawnChance = 50};
    VehicleZoneDistribution.trafficjams.vehicles["Base.SC_ChevroletM1010"] = {index = -1, spawnChance = 30};
    VehicleZoneDistribution.trafficjams.vehicles["Base.SC_AMGeneralM35A1"] = {index = -1, spawnChance = 10};
    VehicleZoneDistribution.trafficjams.vehicles["Base.SC_AMGeneralM998"] = {index = -1, spawnChance = 50};
    VehicleZoneDistribution.trafficjams.vehicles["Base.SC_AMGeneralM1025"] = {index = -1, spawnChance = 10};
    VehicleZoneDistribution.trafficjams.vehicles["Base.SC_AMGeneralM1025MP"] = {index = -1, spawnChance = 5};
    VehicleZoneDistribution.trafficjams.vehicles["Base.SC_AMGeneralM1025MPTan"] = {index = -1, spawnChance = 5};
    VehicleZoneDistribution.trafficjams.vehicles["Base.SC_FordExplorer"] = {index = -1, spawnChance = 5};
    VehicleZoneDistribution.trafficjams.vehicles["Base.SC_FordTaurus"] = {index = -1, spawnChance = 15};
    VehicleZoneDistribution.trafficjams.vehicles["Base.SC_HondaAccord"] = {index = -1, spawnChance = 15};
    VehicleZoneDistribution.trafficjams.vehicles["Base.SC_VWRabbit"] = {index = -1, spawnChance = 15};
    VehicleZoneDistribution.trafficjams.vehicles["Base.SC_MazdaB2000"] = {index = -1, spawnChance = 10};
    VehicleZoneDistribution.trafficjams.vehicles["Base.SC_FordCrownVictoria85"] = {index = -1, spawnChance = 10};
    VehicleZoneDistribution.trafficjams.vehicles["Base.SC_FordCrownVictoria85Taxi"] = {index = -1, spawnChance = 1};
    VehicleZoneDistribution.trafficjams.vehicles["Base.SC_FordCrownVictoria85StatePolice"] = {index = -1, spawnChance = 1};
    VehicleZoneDistribution.trafficjams.vehicles["Base.SC_FordCrownVictoria85ParkRanger"] = {index = -1, spawnChance = 1};
    VehicleZoneDistribution.trafficjams.vehicles["Base.SC_FordF350Ambulance"] = {index = -1, spawnChance = 10};
    VehicleZoneDistribution.trafficjams.vehicles["Base.SC_GrummanLLV"] = {index = -1, spawnChance = 5};
    VehicleZoneDistribution.trafficjams.vehicles["Base.SC_FordF700ArmoredBank"] = {index = -1, spawnChance = 1};
    VehicleZoneDistribution.trafficjams.vehicles["Base.SC_JeepCJ7"] = {index = -1, spawnChance = 5};
    VehicleZoneDistribution.trafficjams.vehicles["Base.SC_JeepCherokee"] = {index = -1, spawnChance = 5};
    VehicleZoneDistribution.trafficjams.vehicles["Base.SC_PlymouthVoyager"] = {index = -1, spawnChance = 10};
    VehicleZoneDistribution.trafficjams.vehicles["Base.SC_VWRabbitPizza"] = {index = -1, spawnChance = 5};
    VehicleZoneDistribution.trafficjams.vehicles["Base.SC_GeoTracker"] = {index = -1, spawnChance = 10};
    VehicleZoneDistribution.trafficjams.vehicles["Base.SC_FordBronco"] = {index = -1, spawnChance = 6};
    VehicleZoneDistribution.trafficjams.vehicles["Base.SC_FordF150"] = {index = -1, spawnChance = 5};
    VehicleZoneDistribution.trafficjams.vehicles["Base.SC_FordMustang90"] = {index = -1, spawnChance = 5};
    VehicleZoneDistribution.trafficjams.vehicles["Base.SC_FordMustang90Undercover"] = {index = -1, spawnChance = 3};
    VehicleZoneDistribution.trafficjams.vehicles["Base.SC_ChevroletK5Blazer"] = {index = -1, spawnChance = 5};
    VehicleZoneDistribution.trafficjams.vehicles["Base.SC_ChevroletK5BlazerFossoil"] = {index = -1, spawnChance = 1};
    VehicleZoneDistribution.trafficjams.vehicles["Base.SC_ChevroletK5BlazerMcCoys"] = {index = -1, spawnChance = 1};
    VehicleZoneDistribution.trafficjams.vehicles["Base.SC_ChevroletK5BlazerParkRanger"] = {index = -1, spawnChance = 0.5};
    VehicleZoneDistribution.trafficjams.vehicles["Base.SC_ChevroletCaprice85"] = {index = -1, spawnChance = 15};
    VehicleZoneDistribution.trafficjams.vehicles["Base.SC_ChevroletSuburban"] = {index = -1, spawnChance = 0.5};
    VehicleZoneDistribution.trafficjams.vehicles["Base.SC_ChevroletCavalier"] = {index = -1, spawnChance = 5};
    VehicleZoneDistribution.trafficjams.vehicles["Base.SC_ChevroletCamaro87"] = {index = -1, spawnChance = 1};
    VehicleZoneDistribution.trafficjams.vehicles["Base.SC_ChevroletP30"] = {index = -1, spawnChance = 1};
    VehicleZoneDistribution.trafficjams.vehicles["Base.SC_ChevroletP30Mail"] = {index = -1, spawnChance = 0.5};
    VehicleZoneDistribution.trafficjams.vehicles["Base.SC_ChevroletP30Heralds"] = {index = -1, spawnChance = 0.5};
    VehicleZoneDistribution.trafficjams.vehicles["Base.SC_ChevroletP30Scarlet"] = {index = -1, spawnChance = 0.5};
    VehicleZoneDistribution.trafficjams.vehicles["Base.SC_ChevroletP30BunnyBread"] = {index = -1, spawnChance = 5};
    VehicleZoneDistribution.trafficjams.vehicles["Base.SC_ChevroletP30Greenes"] = {index = -1, spawnChance = 5};
    VehicleZoneDistribution.trafficjams.vehicles["Base.SC_ChevroletG30"] = {index = -1, spawnChance = 10};
    VehicleZoneDistribution.trafficjams.vehicles["Base.SC_ChevroletG30Seats"] = {index = -1, spawnChance = 1};
    VehicleZoneDistribution.trafficjams.vehicles["Base.SC_ChevroletG30Mail"] = {index = -1, spawnChance = 5};
    VehicleZoneDistribution.trafficjams.vehicles["Base.SC_ChevroletG30McCoy"] = {index = -1, spawnChance = 5};
    VehicleZoneDistribution.trafficjams.vehicles["Base.SC_ChevroletG30Spiffo"] = {index = -1, spawnChance = 5};
    VehicleZoneDistribution.trafficjams.vehicles["Base.SC_ChevroletG30Fossoil"] = {index = -1, spawnChance = 5};
    VehicleZoneDistribution.trafficjams.vehicles["Base.SC_ChevroletG30LectroMax"] = {index = -1, spawnChance = 5};
    VehicleZoneDistribution.trafficjams.vehicles["Base.SC_ChevroletG30MassGenFac"] = {index = -1, spawnChance = 5};
    VehicleZoneDistribution.trafficjams.vehicles["Base.SC_ChevroletG30Ambulance"] = {index = -1, spawnChance = 5};
    VehicleZoneDistribution.trafficjams.vehicles["Base.SC_ChevroletG30SpecialForces"] = {index = -1, spawnChance = 3};
    VehicleZoneDistribution.trafficjams.vehicles["Base.SC_ChevroletG30BoxVan"] = {index = -1, spawnChance = 0.5};
    VehicleZoneDistribution.trafficjams.vehicles["Base.SC_FordF700BoxTruck"] = {index = -1, spawnChance = 5};
    VehicleZoneDistribution.trafficjams.vehicles["Base.SC_FordF700DumpTruck"] = {index = -1, spawnChance = 3};
    VehicleZoneDistribution.trafficjams.vehicles["Base.SC_FordF700MacTools"] = {index = -1, spawnChance = 0.1};
    VehicleZoneDistribution.trafficjams.vehicles["Base.SC_FordF700GigaMart"] = {index = -1, spawnChance = 3};
    VehicleZoneDistribution.trafficjams.vehicles["Base.SC_FordF700Greenes"] = {index = -1, spawnChance = 3};
    VehicleZoneDistribution.trafficjams.vehicles["Base.SC_FordF700BunnyBread"] = {index = -1, spawnChance = 3};
    VehicleZoneDistribution.trafficjams.vehicles["Base.SC_MackDM800Garbage"] = {index = -1, spawnChance = 5};
    VehicleZoneDistribution.trafficjams.vehicles["Base.SC_ChevroletC70GrainTruck"] = {index = -1, spawnChance = 5};
    VehicleZoneDistribution.trafficjams.vehicles["Base.SC_FordMustang90JeffersonPolice"] = {index = -1, spawnChance = 3};
    VehicleZoneDistribution.trafficjams.vehicles["Base.SC_FordMustang90StatePolice"] = {index = -1, spawnChance = 3};
    VehicleZoneDistribution.trafficjams.vehicles["Base.SC_FordCrownVictoria"] = {index = -1, spawnChance = 3};
    VehicleZoneDistribution.trafficjams.vehicles["Base.SC_FordCrownVictoria85LouisvillePolice"] = {index = -1, spawnChance = 3};
    VehicleZoneDistribution.trafficjams.vehicles["Base.SC_FordCrownVictoria92JeffersonSheriff"] = {index = -1, spawnChance = 3};
    VehicleZoneDistribution.trafficjams.vehicles["Base.SC_ToyotaCamry"] = {index = -1, spawnChance = 10};
    VehicleZoneDistribution.trafficjams.chanceToPartDamage = 10;
    VehicleZoneDistribution.trafficjams.baseVehicleQuality = 1.1;
	VehicleZoneDistribution.trafficjams.chanceToSpawnKey = 80;

end