if VehicleZoneDistribution then

    VehicleZoneDistribution.parkingstall.vehicles["Base.SC_FordExplorer"] = {index = -1, spawnChance = 5};
    VehicleZoneDistribution.parkingstall.vehicles["Base.SC_HondaAccord"] = {index = -1, spawnChance = 15};
    VehicleZoneDistribution.parkingstall.vehicles["Base.SC_VWRabbit"] = {index = -1, spawnChance = 10};
    VehicleZoneDistribution.parkingstall.vehicles["Base.SC_MazdaB2000"] = {index = -1, spawnChance = 15};
    VehicleZoneDistribution.parkingstall.vehicles["Base.SC_FordCrownVictoria85"] = {index = -1, spawnChance = 10};
    VehicleZoneDistribution.parkingstall.vehicles["Base.SC_FordCrownVictoria92"] = {index = -1, spawnChance = 10};
    VehicleZoneDistribution.parkingstall.vehicles["Base.SC_FordCrownVictoriaStatePolice85"] = {index = -1, spawnChance = 1};
    VehicleZoneDistribution.parkingstall.vehicles["Base.SC_FordF350Ambulance"] = {index = -1, spawnChance = 1};
    VehicleZoneDistribution.parkingstall.vehicles["Base.SC_GrummanLLV"] = {index = -1, spawnChance = 1};
    VehicleZoneDistribution.parkingstall.vehicles["Base.SC_FordF700ArmoredBank"] = {index = -1, spawnChance = 0.01};
    VehicleZoneDistribution.parkingstall.vehicles["Base.SC_JeepCJ7"] = {index = -1, spawnChance = 5};
    VehicleZoneDistribution.parkingstall.vehicles["Base.SC_JeepCherokee"] = {index = -1, spawnChance = 1};
    VehicleZoneDistribution.parkingstall.vehicles["Base.SC_PlymouthVoyager"] = {index = -1, spawnChance = 5};
    VehicleZoneDistribution.parkingstall.vehicles["Base.SC_VWRabbitPizza"] = {index = -1, spawnChance = 1};
    VehicleZoneDistribution.parkingstall.vehicles["Base.SC_GeoTracker"] = {index = -1, spawnChance = 5};
    VehicleZoneDistribution.parkingstall.vehicles["Base.SC_FordBronco"] = {index = -1, spawnChance = 5};
    VehicleZoneDistribution.parkingstall.vehicles["Base.SC_FordF150"] = {index = -1, spawnChance = 5};
    VehicleZoneDistribution.parkingstall.vehicles["Base.SC_FordMustang90"] = {index = -1, spawnChance = 5};
    VehicleZoneDistribution.parkingstall.vehicles["Base.SC_FordMustang90Undercover"] = {index = -1, spawnChance = 0.2};
    VehicleZoneDistribution.parkingstall.vehicles["Base.SC_ChevroletK5Blazer"] = {index = -1, spawnChance = 5};
    VehicleZoneDistribution.parkingstall.vehicles["Base.SC_ChevroletK5BlazerFossoil"] = {index = -1, spawnChance = 1};
    VehicleZoneDistribution.parkingstall.vehicles["Base.SC_ChevroletK5BlazerMcCoys"] = {index = -1, spawnChance = 1};
    VehicleZoneDistribution.parkingstall.vehicles["Base.SC_ChevroletK5BlazerParkRanger"] = {index = -1, spawnChance = 0.5};
    VehicleZoneDistribution.parkingstall.vehicles["Base.SC_ChevroletCaprice85"] = {index = -1, spawnChance = 15};
    VehicleZoneDistribution.parkingstall.vehicles["Base.SC_ChevroletCapriceStatePolice85"] = {index = -1, spawnChance = 0.3};
    VehicleZoneDistribution.parkingstall.vehicles["Base.SC_ChevroletSuburban"] = {index = -1, spawnChance = 0.5};
    VehicleZoneDistribution.parkingstall.vehicles["Base.SC_ChevroletCavalier"] = {index = -1, spawnChance = 10};
    VehicleZoneDistribution.parkingstall.vehicles["Base.SC_ChevroletCamaro87"] = {index = -1, spawnChance = 1};
    VehicleZoneDistribution.parkingstall.vehicles["Base.SC_ChevroletP30"] = {index = -1, spawnChance = 1};
    VehicleZoneDistribution.parkingstall.vehicles["Base.SC_ChevroletP30Mail"] = {index = -1, spawnChance = 0.5};
    VehicleZoneDistribution.parkingstall.vehicles["Base.SC_ChevroletP30Heralds"] = {index = -1, spawnChance = 0.5};
    VehicleZoneDistribution.parkingstall.vehicles["Base.SC_ChevroletP30Scarlet"] = {index = -1, spawnChance = 0.5};
    VehicleZoneDistribution.parkingstall.vehicles["Base.SC_ChevroletP30BunnyBread"] = {index = -1, spawnChance = 0.5};
    VehicleZoneDistribution.parkingstall.vehicles["Base.SC_ChevroletP30Greenes"] = {index = -1, spawnChance = 0.5};
    VehicleZoneDistribution.parkingstall.vehicles["Base.SC_ChevroletG30"] = {index = -1, spawnChance = 1};
    VehicleZoneDistribution.parkingstall.vehicles["Base.SC_ChevroletG30Seats"] = {index = -1, spawnChance = 1};
    VehicleZoneDistribution.parkingstall.vehicles["Base.SC_ChevroletG30Mail"] = {index = -1, spawnChance = 1};
    VehicleZoneDistribution.parkingstall.vehicles["Base.SC_ChevroletG30McCoy"] = {index = -1, spawnChance = 1};
    VehicleZoneDistribution.parkingstall.vehicles["Base.SC_ChevroletG30Spiffo"] = {index = -1, spawnChance = 1};
    VehicleZoneDistribution.parkingstall.vehicles["Base.SC_ChevroletG30Fossoil"] = {index = -1, spawnChance = 1};
    VehicleZoneDistribution.parkingstall.vehicles["Base.SC_ChevroletG30LectroMax"] = {index = -1, spawnChance = 1};
    VehicleZoneDistribution.parkingstall.vehicles["Base.SC_ChevroletG30MassGenFac"] = {index = -1, spawnChance = 1};
    VehicleZoneDistribution.parkingstall.vehicles["Base.SC_ChevroletG30SpecialForces"] = {index = -1, spawnChance = 0.1};
    VehicleZoneDistribution.parkingstall.vehicles["Base.SC_ChevroletG30BoxVan"] = {index = -1, spawnChance = 0.5};
    VehicleZoneDistribution.parkingstall.vehicles["Base.SC_FordF700BoxTruck"] = {index = -1, spawnChance = 0.5};
    VehicleZoneDistribution.parkingstall.vehicles["Base.SC_FordF700DumpTruck"] = {index = -1, spawnChance = 0.5};
    VehicleZoneDistribution.parkingstall.vehicles["Base.SC_FordF700MacTools"] = {index = -1, spawnChance = 0.5};       
    VehicleZoneDistribution.parkingstall.vehicles["Base.SC_FordF700GigaMart"] = {index = -1, spawnChance = 0.5};     
    VehicleZoneDistribution.parkingstall.vehicles["Base.SC_FordF700Greenes"] = {index = -1, spawnChance = 0.5};
    VehicleZoneDistribution.parkingstall.vehicles["Base.SC_FordF700BunnyBread"] = {index = -1, spawnChance = 0.5};       
    VehicleZoneDistribution.parkingstall.vehicles["Base.SC_MackDM800Garbage"] = {index = -1, spawnChance = 0.2};       
    VehicleZoneDistribution.parkingstall.chanceToPartDamage = 5;
    
    VehicleZoneDistribution.medium.vehicles["Base.SC_ChevroletP30Greenes"] = {index = -1, spawnChance = 1};
    VehicleZoneDistribution.medium.vehicles["Base.SC_ChevroletP30BunnyBread"] = {index = -1, spawnChance = 1};
    VehicleZoneDistribution.medium.vehicles["Base.SC_FordF700BoxTruck"] = {index = -1, spawnChance = 5};
    VehicleZoneDistribution.medium.vehicles["Base.SC_FordF700PanelTruck"] = {index = -1, spawnChance = 5};
    VehicleZoneDistribution.medium.vehicles["Base.SC_FordF700DumpTruck"] = {index = -1, spawnChance = 5};
    VehicleZoneDistribution.medium.vehicles["Base.SC_ChevroletCaprice85"] = {index = -1, spawnChance = 15};
    VehicleZoneDistribution.medium.chanceToPartDamage = 10;
    
    VehicleZoneDistribution.good.vehicles["Base.SC_P30Greenes"] = {index = -1, spawnChance = 0.5};
    VehicleZoneDistribution.good.vehicles["Base.SC_P30BunnyBread"] = {index = -1, spawnChance = 0.5};
    VehicleZoneDistribution.good.vehicles["Base.SC_ChevroletCaprice85"] = {index = -1, spawnChance = 35};
    VehicleZoneDistribution.good.vehicles["Base.SC_JeepCherokee"] = {index = -1, spawnChance = 35};
    VehicleZoneDistribution.good.vehicles["Base.SC_MazdaB2000"] = {index = -1, spawnChance = 35};
    VehicleZoneDistribution.good.vehicles["Base.SC_GeoTracker"] = {index = -1, spawnChance = 35};
    VehicleZoneDistribution.good.vehicles["Base.SC_FordF150"] = {index = -1, spawnChance = 35};
    VehicleZoneDistribution.good.vehicles["Base.SC_FordBronco"] = {index = -1, spawnChance = 35};
    VehicleZoneDistribution.good.vehicles["Base.SC_PlymouthVoyager"] = {index = -1, spawnChance = 30};
    VehicleZoneDistribution.good.vehicles["Base.SC_Porsche911G50"] = {index = -1, spawnChance = 5};
    VehicleZoneDistribution.good.vehicles["Base.SC_FordMustang90"] = {index = -1, spawnChance = 25};
    VehicleZoneDistribution.good.vehicles["Base.SC_CadillacBrougham"] = {index = -1, spawnChance = 5};
    VehicleZoneDistribution.good.vehicles["Base.SC_Mercedes280"] = {index = -1, spawnChance = 5};
    VehicleZoneDistribution.good.vehicles["Base.SC_BMW520i"] = {index = -1, spawnChance = 5};
    VehicleZoneDistribution.good.vehicles["Base.SC_FordTaurus"] = {index = -1, spawnChance = 25};
    VehicleZoneDistribution.good.vehicles["Base.SC_ChevroletCavalier"] = {index = -1, spawnChance = 25};
    VehicleZoneDistribution.good.chanceToPartDamage = 5;

    VehicleZoneDistribution.sport.vehicles["Base.SC_FordMustang90"] = {index = -1, spawnChance = 70};
    VehicleZoneDistribution.sport.vehicles["Base.SC_FordBronco"] = {index = -1, spawnChance = 70};
    VehicleZoneDistribution.sport.vehicles["Base.SC_Porsche911G50"] = {index = -1, spawnChance = 10};
    VehicleZoneDistribution.sport.vehicles["Base.SC_JeepCherokee"] = {index = -1, spawnChance = 70};
    VehicleZoneDistribution.sport.vehicles["Base.SC_BMW520i"] = {index = -1, spawnChance = 50};
    VehicleZoneDistribution.sport.vehicles["Base.SC_CadillacBrougham"] = {index = -1, spawnChance = 80};
    VehicleZoneDistribution.sport.vehicles["Base.SC_ChevroletSuburban"] = {index = -1, spawnChance = 50};
    VehicleZoneDistribution.sport.vehicles["Base.SC_ChevroletCamaro87"] = {index = -1, spawnChance = 50};

    VehicleZoneDistribution.police.vehicles["Base.SC_ChevroletP30SWAT"] = {index = -1, spawnChance = 1};
    VehicleZoneDistribution.police.vehicles["Base.SC_ChevroletSuburbanStatePolice"] = {index = -1, spawnChance = 5};
    VehicleZoneDistribution.police.vehicles["Base.SC_FordMustang90JeffersonCounty"] = {index = -1, spawnChance = 1};
    VehicleZoneDistribution.police.vehicles["Base.SC_FordMustang90StatePolice"] = {index = -1, spawnChance = 10};
    VehicleZoneDistribution.police.vehicles["Base.SC_FordMustang90Undercover"] = {index = -1, spawnChance = 5};
    VehicleZoneDistribution.police.vehicles["Base.SC_FordCrownVictoriaStatePolice85"] = {index = -1, spawnChance = 50};
    VehicleZoneDistribution.police.vehicles["Base.SC_FordCrownVictoriaJefferson92"] = {index = -1, spawnChance = 1};
    VehicleZoneDistribution.police.vehicles["Base.SC_FordCrownVictoriaMuhlen92"] = {index = -1, spawnChance = 1};
    VehicleZoneDistribution.police.vehicles["Base.SC_FordCrownVictoriaWarren92"] = {index = -1, spawnChance = 1};
    VehicleZoneDistribution.police.vehicles["Base.SC_FordCrownVictoriaMeade92"] = {index = -1, spawnChance = 1};
    VehicleZoneDistribution.police.vehicles["Base.SC_FordF700ArmoredPolice"] = {index = -1, spawnChance = 1};
    VehicleZoneDistribution.police.chanceToPartDamage = 5;

    VehicleZoneDistribution.postal.vehicles["Base.SC_GrummanLLV"] = {index = -1, spawnChance = 100};
    VehicleZoneDistribution.postal.vehicles["Base.SC_ChevroletP30Mail"] = {index = -1, spawnChance = 25};
    VehicleZoneDistribution.postal.vehicles["Base.SC_ChevroletG30Mail"] = {index = -1, spawnChance = 25};
    VehicleZoneDistribution.postal.chanceToPartDamage = 5;

    VehicleZoneDistribution.mccoy.vehicles["Base.SC_FordF700BoxTruck"] = {index = -1, spawnChance = 25};
    VehicleZoneDistribution.mccoy.vehicles["Base.SC_FordF700MacTools"] = {index = -1, spawnChance = 25};
    VehicleZoneDistribution.mccoy.vehicles["Base.SC_FordF700PanelTruck"] = {index = -1, spawnChance = 25};
    VehicleZoneDistribution.mccoy.vehicles["Base.SC_FordF700DumpTruck"] = {index = -1, spawnChance = 25};
    VehicleZoneDistribution.mccoy.vehicles["Base.SC_ChevroletG30McCoy"] = {index = -1, spawnChance = 25};
    VehicleZoneDistribution.mccoy.vehicles["Base.SC_ChevroletG30BoxVan"] = {index = -1, spawnChance = 25};
    VehicleZoneDistribution.mccoy.vehicles["Base.SC_ChevroletK5BlazerMcCoys"] = {index = -1, spawnChance = 25};
    VehicleZoneDistribution.mccoy.vehicles["Base.SC_ChevroletK5BlazerFossoil"] = {index = -1, spawnChance = 25};
    VehicleZoneDistribution.mccoy.chanceToPartDamage = 25;
    
    VehicleZoneDistribution.knoxdisti.vehicles["Base.SC_ChevroletCapriceLVPD85"] = {index = -1, spawnChance = 5};
    VehicleZoneDistribution.knoxdisti.vehicles["Base.SC_FordCrownVictoriaLVPD85"] = {index = -1, spawnChance = 5};
    VehicleZoneDistribution.knoxdisti.vehicles["Base.SC_FordCrownVictoriaJefferson92"] = {index = -1, spawnChance = 5};
    VehicleZoneDistribution.knoxdisti.vehicles["Base.SC_FordCrownVictoriaLVPD92"] = {index = -1, spawnChance = 5};
    VehicleZoneDistribution.knoxdisti.vehicles["Base.SC_M1009FireLV"] = {index = -1, spawnChance = 5};
    VehicleZoneDistribution.knoxdisti.vehicles["Base.SC_JeepCherokeeAudubon"] = {index = -1, spawnChance = 10};
    VehicleZoneDistribution.knoxdisti.chanceToPartDamage = 5;

    VehicleZoneDistribution.massgenfac.vehicles["Base.SC_ChevroletCapriceLVPD85"] = {index = -1, spawnChance = 5};
    VehicleZoneDistribution.massgenfac.vehicles["Base.SC_FordCrownVictoriaLVPD92"] = {index = -1, spawnChance = 5};
    VehicleZoneDistribution.massgenfac.vehicles["Base.SC_M1009FireLV"] = {index = -1, spawnChance = 5};
    VehicleZoneDistribution.massgenfac.vehicles["Base.SC_JeepCherokeeAudubon"] = {index = -1, spawnChance = 5};
    VehicleZoneDistribution.massgenfac.vehicles["Base.SC_ChevroletG30BoxVan"] = {index = -1, spawnChance = 25};
    VehicleZoneDistribution.massgenfac.vehicles["Base.SC_ChevroletK5BlazerFossoil"] = {index = -1, spawnChance = 25};
    VehicleZoneDistribution.massgenfac.chanceToPartDamage = 10;

    VehicleZoneDistribution.network3.vehicles["Base.SC_ChevroletCapriceLVPD85"] = {index = -1, spawnChance = 5};
    VehicleZoneDistribution.network3.vehicles["Base.SC_M1009FireLV"] = {index = -1, spawnChance = 5};
    VehicleZoneDistribution.network3.vehicles["Base.SC_FordCrownVictoriaLVPD85"] = {index = -1, spawnChance = 5};
    VehicleZoneDistribution.network3.vehicles["Base.SC_FordCrownVictoriaLVPD92"] = {index = -1, spawnChance = 3};
    VehicleZoneDistribution.network3.vehicles["Base.SC_JeepCherokeeAudubon"] = {index = -1, spawnChance = 10};
    VehicleZoneDistribution.network3.chanceToPartDamage = 5;

    VehicleZoneDistribution.kyheralds.vehicles["Base.SC_ChevroletCapriceLVPD85"] = {index = -1, spawnChance = 5};
    VehicleZoneDistribution.kyheralds.vehicles["Base.SC_FordCrownVictoriaLVPD85"] = {index = -1, spawnChance = 5};
    VehicleZoneDistribution.kyheralds.vehicles["Base.SC_FordCrownVictoriaLVPD92"] = {index = -1, spawnChance = 3};
    VehicleZoneDistribution.kyheralds.vehicles["Base.SC_JeepCherokeeAudubon"] = {index = -1, spawnChance = 10};
    VehicleZoneDistribution.kyheralds.chanceToPartDamage = 5;

    VehicleZoneDistribution.junkyard.vehicles["Base.SC_FordF700PanelTruck"] = {index = -1, spawnChance = 5};  
    VehicleZoneDistribution.junkyard.vehicles["Base.SC_FordF700BoxTruck"] = {index = -1, spawnChance = 5};  
    VehicleZoneDistribution.junkyard.vehicles["Base.SC_FordF700DumpTruck"] = {index = -1, spawnChance = 5};  
    VehicleZoneDistribution.junkyard.vehicles["Base.SC_ChevroletG30SpecialForces"] = {index = -1, spawnChance = 5};  
    VehicleZoneDistribution.junkyard.chanceToPartDamage = 60;

    VehicleZoneDistribution.trafficjams.vehicles["Base.SUV"] = {index = -1, spawnChance = 7};    
    VehicleZoneDistribution.trafficjams.vehicles["Base.LuxuryCar"] = {index = -1, spawnChance = 6};
    VehicleZoneDistribution.trafficjams.vehicles["Base.SportsCar"] = {index = -1, spawnChance = 10};
    VehicleZoneDistribution.trafficjams.vehicles["Base.CarLights"] = {index = -1, spawnChance = 1};
    VehicleZoneDistribution.trafficjams.vehicles["Base.CarLightsPolice"] = {index = -1, spawnChance = 5};
    VehicleZoneDistribution.trafficjams.vehicles["Base.PickUpVanLightsPolice"] = {index = -1, spawnChance = 5};
    VehicleZoneDistribution.trafficjams.vehicles["Base.SC_ChevroletP30Greenes"] = {index = -1, spawnChance = 5};
    VehicleZoneDistribution.trafficjams.vehicles["Base.SC_ChevroletP30BunnyBread"] = {index = -1, spawnChance = 5};
    VehicleZoneDistribution.trafficjams.vehicles["Base.Offroad"] = {index = -1, spawnChance = 10};      
    VehicleZoneDistribution.trafficjams.vehicles["Base.CarNormal"] = {index = -1, spawnChance = 10}; 
    VehicleZoneDistribution.trafficjams.vehicles["Base.CarTaxi"] = {index = -1, spawnChance = 10}; 
    VehicleZoneDistribution.trafficjams.vehicles["Base.CarTaxi2"] = {index = -1, spawnChance = 10};   
    VehicleZoneDistribution.trafficjams.vehicles["Base.PickUpVan"] = {index = -1, spawnChance = 10};  
    VehicleZoneDistribution.trafficjams.vehicles["Base.PickUpTruck"] = {index = -1, spawnChance = 10};    
    VehicleZoneDistribution.trafficjams.vehicles["Base.SC_GeoTracker"] = {index = -1, spawnChance = 10};
    VehicleZoneDistribution.trafficjams.vehicles["Base.SC_JeepCherokee"] = {index = -1, spawnChance = 5};  
    VehicleZoneDistribution.trafficjams.vehicles["Base.SC_FordBronco"] = {index = -1, spawnChance = 6};
    VehicleZoneDistribution.trafficjams.vehicles["Base.SC_ToyotaCamry"] = {index = -1, spawnChance = 10};    
    VehicleZoneDistribution.trafficjams.vehicles["Base.SC_FordF150"] = {index = -1, spawnChance = 5};    
    VehicleZoneDistribution.trafficjams.vehicles["Base.SC_MazdaB2000"] = {index = -1, spawnChance = 10};    
    VehicleZoneDistribution.trafficjams.vehicles["Base.SC_PlymouthVoyager"] = {index = -1, spawnChance = 10};
    VehicleZoneDistribution.trafficjams.vehicles["Base.SC_FordF350Ambulance"] = {index = -1, spawnChance = 10};
    VehicleZoneDistribution.trafficjams.vehicles["Base.SC_FordF700DumpTruck"] = {index = -1, spawnChance = 5};
    VehicleZoneDistribution.trafficjams.vehicles["Base.SC_FordF700BoxTruckMacTools"] = {index = -1, spawnChance = 10};       
    VehicleZoneDistribution.trafficjams.vehicles["Base.SC_FordF700BoxTruckGigaMart"] = {index = -1, spawnChance = 10};     
    VehicleZoneDistribution.trafficjams.vehicles["Base.SC_FordF700BoxTruckGreenes"] = {index = -1, spawnChance = 10};
    VehicleZoneDistribution.trafficjams.vehicles["Base.SC_FordF700BoxTruckBunnyBread"] = {index = -1, spawnChance = 10};             
    VehicleZoneDistribution.trafficjams.vehicles["Base.SC_FordF700BoxTruck"] = {index = -1, spawnChance = 5};    
    VehicleZoneDistribution.trafficjams.vehicles["Base.SC_FordF700ArmoredBank"] = {index = -1, spawnChance = 1};  
    VehicleZoneDistribution.trafficjams.vehicles["Base.SC_ChevroletC70GrainTruck"] = {index = -1, spawnChance = 5};  
    VehicleZoneDistribution.trafficjams.vehicles["Base.SC_FordMustang90Undercover"] = {index = -1, spawnChance = 3};
    VehicleZoneDistribution.trafficjams.vehicles["Base.SC_FordMustang90JeffersonCounty"] = {index = -1, spawnChance = 3};
    VehicleZoneDistribution.trafficjams.vehicles["Base.SC_FordMustang90StatePolice"] = {index = -1, spawnChance = 3};
    VehicleZoneDistribution.trafficjams.vehicles["Base.SC_ChevroletCavalier"] = {index = -1, spawnChance = 5};
    VehicleZoneDistribution.trafficjams.vehicles["Base.SC_MercedesSL500"] = {index = -1, spawnChance = 5};
    VehicleZoneDistribution.trafficjams.vehicles["Base.SC_GrummanLLV"] = {index = -1, spawnChance = 5};
    VehicleZoneDistribution.trafficjams.vehicles["Base.SC_MackDM800Garbage"] = {index = -1, spawnChance = 5};
    VehicleZoneDistribution.trafficjams.vehicles["Base.SC_FordCrownVictoria92"] = {index = -1, spawnChance = 3};
    VehicleZoneDistribution.trafficjams.vehicles["Base.SC_FordCrownVictoriaLVPD92"] = {index = -1, spawnChance = 3};
    VehicleZoneDistribution.trafficjams.vehicles["Base.SC_FordCrownVictoriaJefferson92"] = {index = -1, spawnChance = 3};
    VehicleZoneDistribution.trafficjams.vehicles["Base.SC_ChevroletG30SpecialForces"] = {index = -1, spawnChance = 3};
    VehicleZoneDistribution.trafficjams.vehicles["Base.SC_VWRabbitPizza"] = {index = -1, spawnChance = 5};
    VehicleZoneDistribution.trafficjams.vehicles["Base.SC_M35A1Burnt"] = {index = -1, spawnChance = 5};  
    VehicleZoneDistribution.trafficjams.vehicles["Base.SC_M35A1Crashed"] = {index = -1, spawnChance = 1};  
    VehicleZoneDistribution.trafficjams.vehicles["Base.SC_M35A1CrashedTurned"] = {index = -1, spawnChance = 5};  
    VehicleZoneDistribution.trafficjams.chanceToPartDamage = 50;

end